// Code generated by ogen, DO NOT EDIT.

package neon

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AcceptProjectTransferRequest implements acceptProjectTransferRequest operation.
	//
	// Accepts a transfer request for the specified project, transferring it to the specified organization
	// or user. If org_id is not passed, the project will be transferred to the current user or
	// organization account.
	//
	// PUT /projects/{project_id}/transfer_requests/{request_id}
	AcceptProjectTransferRequest(ctx context.Context, req OptAcceptProjectTransferRequestReq, params AcceptProjectTransferRequestParams) (AcceptProjectTransferRequestRes, error)
	// AddBranchNeonAuthOauthProvider implements addBranchNeonAuthOauthProvider operation.
	//
	// Adds a OAuth provider to the specified project.
	//
	// POST /projects/{project_id}/branches/{branch_id}/auth/oauth_providers
	AddBranchNeonAuthOauthProvider(ctx context.Context, req *NeonAuthAddOAuthProviderRequest, params AddBranchNeonAuthOauthProviderParams) (*NeonAuthOauthProvider, error)
	// AddBranchNeonAuthTrustedDomain implements addBranchNeonAuthTrustedDomain operation.
	//
	// Adds a domain to the redirect_uri whitelist for the specified project.
	//
	// POST /projects/{project_id}/branches/{branch_id}/auth/domains
	AddBranchNeonAuthTrustedDomain(ctx context.Context, req *NeonAuthAddDomainToRedirectURIWhitelistRequest, params AddBranchNeonAuthTrustedDomainParams) error
	// AddNeonAuthDomainToRedirectURIWhitelist implements addNeonAuthDomainToRedirectURIWhitelist operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/domains` instead. Adds a domain
	// to the redirect_uri whitelist for the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /projects/{project_id}/auth/domains
	AddNeonAuthDomainToRedirectURIWhitelist(ctx context.Context, req *NeonAuthAddDomainToRedirectURIWhitelistRequest, params AddNeonAuthDomainToRedirectURIWhitelistParams) error
	// AddNeonAuthOauthProvider implements addNeonAuthOauthProvider operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/oauth_providers` instead. Adds a
	// OAuth provider to the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /projects/{project_id}/auth/oauth_providers
	AddNeonAuthOauthProvider(ctx context.Context, req *NeonAuthAddOAuthProviderRequest, params AddNeonAuthOauthProviderParams) (*NeonAuthOauthProvider, error)
	// AddProjectJWKS implements addProjectJWKS operation.
	//
	// Add a new JWKS URL to a project, such that it can be used for verifying JWTs used as the
	// authentication mechanism for the specified project.
	// The URL must be a valid HTTPS URL that returns a JSON Web Key Set.
	// The `provider_name` field allows you to specify which authentication provider you're using (e.g.,
	// Clerk, Auth0, AWS Cognito, etc.).
	// The `branch_id` can be used to specify on which branches the JWKS URL will be accepted. If not
	// specified, then it will work on any branch.
	// The `role_names` can be used to specify for which roles the JWKS URL will be accepted. If not
	// specified, then default roles will be used (authenticator, authenticated and anonymous).
	// The `jwt_audience` can be used to specify which "aud" values should be accepted by Neon in the
	// JWTs that are used for authentication.
	//
	// POST /projects/{project_id}/jwks
	AddProjectJWKS(ctx context.Context, req *AddProjectJWKSRequest, params AddProjectJWKSParams) (*JWKSCreationOperation, error)
	// AssignOrganizationVPCEndpoint implements assignOrganizationVPCEndpoint operation.
	//
	// Assigns a VPC endpoint to a Neon organization or updates its existing assignment.
	//
	// POST /organizations/{org_id}/vpc/region/{region_id}/vpc_endpoints/{vpc_endpoint_id}
	AssignOrganizationVPCEndpoint(ctx context.Context, req *VPCEndpointAssignment, params AssignOrganizationVPCEndpointParams) error
	// AssignProjectVPCEndpoint implements assignProjectVPCEndpoint operation.
	//
	// Sets or updates a VPC endpoint restriction for a Neon project.
	// When a VPC endpoint restriction is set, the project only accepts connections
	// from the specified VPC.
	// A VPC endpoint can be set as a restriction only after it is assigned to the
	// parent organization of the Neon project.
	//
	// POST /projects/{project_id}/vpc_endpoints/{vpc_endpoint_id}
	AssignProjectVPCEndpoint(ctx context.Context, req *VPCEndpointAssignment, params AssignProjectVPCEndpointParams) error
	// CountProjectBranches implements countProjectBranches operation.
	//
	// Retrieves the total number of branches in the specified project.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	//
	// GET /projects/{project_id}/branches/count
	CountProjectBranches(ctx context.Context, params CountProjectBranchesParams) (*BranchesCountResponse, error)
	// CreateApiKey implements createApiKey operation.
	//
	// Creates an API key.
	// The `key_name` is a user-specified name for the key.
	// This method returns an `id` and `key`. The `key` is a randomly generated, 64-bit token required to
	// access the Neon API.
	// API keys can also be managed in the Neon Console.
	// See [Manage API keys](https://neon.tech/docs/manage/api-keys/).
	//
	// POST /api_keys
	CreateApiKey(ctx context.Context, req *ApiKeyCreateRequest) (*ApiKeyCreateResponse, error)
	// CreateBranchNeonAuthNewUser implements createBranchNeonAuthNewUser operation.
	//
	// Creates a new user in Neon Auth.
	//
	// POST /projects/{project_id}/branches/{branch_id}/auth/users
	CreateBranchNeonAuthNewUser(ctx context.Context, req *CreateBranchNeonAuthNewUserRequest, params CreateBranchNeonAuthNewUserParams) (*NeonAuthCreateNewUserResponse, error)
	// CreateNeonAuth implements createNeonAuth operation.
	//
	// Enables Neon Auth integrationfor the branch.
	// You can obtain the `project_id` and `branch_id` by listing the projects and branches for your Neon
	// account.
	//
	// POST /projects/{project_id}/branches/{branch_id}/auth
	CreateNeonAuth(ctx context.Context, req *EnableNeonAuthIntegrationRequest, params CreateNeonAuthParams) (*NeonAuthCreateIntegrationResponse, error)
	// CreateNeonAuthIntegration implements createNeonAuthIntegration operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth` instead. Creates a project on a
	// third-party authentication provider's platform for use with Neon Auth.
	// Use this endpoint if the frontend integration flow can't be used.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /projects/auth/create
	CreateNeonAuthIntegration(ctx context.Context, req *NeonAuthCreateIntegrationRequest) (*NeonAuthCreateIntegrationResponse, error)
	// CreateNeonAuthNewUser implements createNeonAuthNewUser operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/users` instead. Creates a new
	// user in Neon Auth.
	// The user will be created in your neon_auth.users_sync table and automatically propagated to your
	// auth project, whether Neon-managed or provider-owned.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /projects/auth/user
	CreateNeonAuthNewUser(ctx context.Context, req *NeonAuthCreateNewUserRequest) (*NeonAuthCreateNewUserResponse, error)
	// CreateNeonAuthProviderSDKKeys implements createNeonAuthProviderSDKKeys operation.
	//
	// Generates SDK or API Keys for the auth provider. These might be called different things depending
	// on the auth provider you're using, but are generally used for setting up the frontend and backend
	// SDKs.
	//
	// POST /projects/auth/keys
	CreateNeonAuthProviderSDKKeys(ctx context.Context, req *NeonAuthCreateAuthProviderSDKKeysRequest) (*NeonAuthCreateIntegrationResponse, error)
	// CreateOrgApiKey implements createOrgApiKey operation.
	//
	// Creates an API key for the specified organization.
	// The `key_name` is a user-specified name for the key.
	// This method returns an `id` and `key`. The `key` is a randomly generated, 64-bit token required to
	// access the Neon API.
	// API keys can also be managed in the Neon Console.
	// See [Manage API keys](https://neon.tech/docs/manage/api-keys/).
	//
	// POST /organizations/{org_id}/api_keys
	CreateOrgApiKey(ctx context.Context, req *OrgApiKeyCreateRequest, params CreateOrgApiKeyParams) (*OrgApiKeyCreateResponse, error)
	// CreateOrganizationInvitations implements createOrganizationInvitations operation.
	//
	// Creates invitations for a specific organization.
	// If the invited user has an existing account, they automatically join as a member.
	// If they don't yet have an account, they are invited to create one, after which they become a
	// member.
	// Each invited user receives an email notification.
	//
	// POST /organizations/{org_id}/invitations
	CreateOrganizationInvitations(ctx context.Context, req *OrganizationInvitesCreateRequest, params CreateOrganizationInvitationsParams) (*OrganizationInvitationsResponse, error)
	// CreateProject implements createProject operation.
	//
	// Creates a Neon project within an organization.
	// You may need to specify an org_id parameter depending on your API key type.
	// Plan limits define how many projects you can create.
	// For more information, see [Manage projects](https://neon.tech/docs/manage/projects/).
	// You can specify a region and Postgres version in the request body.
	// Neon currently supports PostgreSQL 14, 15, 16, and 17.
	// For supported regions and `region_id` values, see [Regions](https://neon.
	// tech/docs/introduction/regions/).
	//
	// POST /projects
	CreateProject(ctx context.Context, req *ProjectCreateRequest) (*CreatedProject, error)
	// CreateProjectBranch implements createProjectBranch operation.
	//
	// Creates a branch in the specified project.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// This method does not require a request body, but you can specify one to create a compute endpoint
	// for the branch or to select a non-default parent branch.
	// By default, the branch is created from the project's default branch with no compute endpoint, and
	// the branch name is auto-generated.
	// To access the branch, you must add an endpoint object. A `read_write` endpoint allows you to
	// perform read and write operations on the branch.
	// Each branch supports one read-write endpoint and multiple read-only endpoints.
	// For related information, see [Manage branches](https://neon.tech/docs/manage/branches/).
	//
	// POST /projects/{project_id}/branches
	CreateProjectBranch(ctx context.Context, req OptCreateProjectBranchReq, params CreateProjectBranchParams) (*CreatedBranch, error)
	// CreateProjectBranchAnonymized implements createProjectBranchAnonymized operation.
	//
	// Creates a new branch with anonymized data using PostgreSQL Anonymizer for static masking.
	// This allows developers to work with masked production data.
	// Optionally, provide `masking_rules` to set initial masking rules for the branch
	// and `start_anonymization` to automatically start anonymization after creation. This
	// combines functionality of updating masking rules and starting anonymization into the
	// branch creation request.
	// **Note**: This endpoint is currently in Beta.
	//
	// POST /projects/{project_id}/branch_anonymized
	CreateProjectBranchAnonymized(ctx context.Context, req *BranchAnonymizedCreateRequest, params CreateProjectBranchAnonymizedParams) (*CreatedBranch, error)
	// CreateProjectBranchDataAPI implements createProjectBranchDataAPI operation.
	//
	// Creates a new instance of Neon Data API in the specified branch.
	// You can obtain the `project_id` and `branch_id` by listing the projects and branches for your Neon
	// account.
	//
	// POST /projects/{project_id}/branches/{branch_id}/data-api/{database_name}
	CreateProjectBranchDataAPI(ctx context.Context, req OptDataAPICreateRequest, params CreateProjectBranchDataAPIParams) (*DataAPICreateResponse, error)
	// CreateProjectBranchDatabase implements createProjectBranchDatabase operation.
	//
	// Creates a database in the specified branch.
	// A branch can have multiple databases.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` by listing the project's branches.
	// For related information, see [Manage databases](https://neon.tech/docs/manage/databases/).
	//
	// POST /projects/{project_id}/branches/{branch_id}/databases
	CreateProjectBranchDatabase(ctx context.Context, req *DatabaseCreateRequest, params CreateProjectBranchDatabaseParams) (*DatabaseOperations, error)
	// CreateProjectBranchRole implements createProjectBranchRole operation.
	//
	// Creates a Postgres role in the specified branch.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` by listing the project's branches.
	// For related information, see [Manage roles](https://neon.tech/docs/manage/roles/).
	// Connections established to the active compute endpoint will be dropped.
	// If the compute endpoint is idle, the endpoint becomes active for a short period of time and is
	// suspended afterward.
	//
	// POST /projects/{project_id}/branches/{branch_id}/roles
	CreateProjectBranchRole(ctx context.Context, req *RoleCreateRequest, params CreateProjectBranchRoleParams) (*RoleOperations, error)
	// CreateProjectEndpoint implements createProjectEndpoint operation.
	//
	// Creates a compute endpoint for the specified branch.
	// An endpoint is a Neon compute instance.
	// There is a maximum of one read-write compute endpoint per branch.
	// If the specified branch already has a read-write compute endpoint, the operation fails.
	// A branch can have multiple read-only compute endpoints.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain `branch_id` by listing the project's branches.
	// A `branch_id` has a `br-` prefix.
	// For supported regions and `region_id` values, see [Regions](https://neon.
	// tech/docs/introduction/regions/).
	// For more information about compute endpoints, see [Manage computes](https://neon.
	// tech/docs/manage/endpoints/).
	//
	// POST /projects/{project_id}/endpoints
	CreateProjectEndpoint(ctx context.Context, req *EndpointCreateRequest, params CreateProjectEndpointParams) (*EndpointOperations, error)
	// CreateProjectTransferRequest implements createProjectTransferRequest operation.
	//
	// Creates a transfer request for the specified project. A transfer request allows
	// the project to be transferred to another account or organization. The request
	// has an expiration time after which it can no longer be used. To accept/claim
	// the transfer request, the recipient user/organization must call the
	// `/projects/{project_id}/transfer_requests/{request_id}` API endpoint, or visit
	// `https://console.neon.tech/app/claim?p={project_id}&tr={request_id}&ru={redirect_url}`
	// in the Neon Console. The `ru` parameter is optional and can be used to redirect
	// the user after accepting the transfer request.
	//
	// POST /projects/{project_id}/transfer_requests
	CreateProjectTransferRequest(ctx context.Context, req OptCreateProjectTransferRequestReq, params CreateProjectTransferRequestParams) (*ProjectTransferRequestResponse, error)
	// CreateSnapshot implements createSnapshot operation.
	//
	// Create a snapshot from the specified branch using the provided parameters.
	// This endpoint may initiate an asynchronous operation.
	// **Note**: This endpoint is currently in Beta.
	//
	// POST /projects/{project_id}/branches/{branch_id}/snapshot
	CreateSnapshot(ctx context.Context, params CreateSnapshotParams) (*CreateSnapshotOK, error)
	// DeleteBranchNeonAuthOauthProvider implements deleteBranchNeonAuthOauthProvider operation.
	//
	// Deletes a OAuth provider from the specified project.
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/auth/oauth_providers/{oauth_provider_id}
	DeleteBranchNeonAuthOauthProvider(ctx context.Context, params DeleteBranchNeonAuthOauthProviderParams) error
	// DeleteBranchNeonAuthTrustedDomain implements deleteBranchNeonAuthTrustedDomain operation.
	//
	// Deletes a domain from the redirect_uri whitelist for the specified project.
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/auth/domains
	DeleteBranchNeonAuthTrustedDomain(ctx context.Context, req *NeonAuthDeleteDomainFromRedirectURIWhitelistRequest, params DeleteBranchNeonAuthTrustedDomainParams) error
	// DeleteBranchNeonAuthUser implements deleteBranchNeonAuthUser operation.
	//
	// Deletes the auth user for the specified project.
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/auth/users/{auth_user_id}
	DeleteBranchNeonAuthUser(ctx context.Context, params DeleteBranchNeonAuthUserParams) error
	// DeleteNeonAuthDomainFromRedirectURIWhitelist implements deleteNeonAuthDomainFromRedirectURIWhitelist operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/domains` instead. Deletes a
	// domain from the redirect_uri whitelist for the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// DELETE /projects/{project_id}/auth/domains
	DeleteNeonAuthDomainFromRedirectURIWhitelist(ctx context.Context, req *NeonAuthDeleteDomainFromRedirectURIWhitelistRequest, params DeleteNeonAuthDomainFromRedirectURIWhitelistParams) error
	// DeleteNeonAuthIntegration implements deleteNeonAuthIntegration operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth` instead.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// DELETE /projects/{project_id}/auth/integration/{auth_provider}
	DeleteNeonAuthIntegration(ctx context.Context, req OptDeleteNeonAuthIntegrationReq, params DeleteNeonAuthIntegrationParams) error
	// DeleteNeonAuthOauthProvider implements deleteNeonAuthOauthProvider operation.
	//
	// DEPRECATED, use
	// `/projects/{project_id}/branches/{branch_id}/auth/oauth_providers/{oauth_provider_id}` instead.
	// Deletes a OAuth provider from the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// DELETE /projects/{project_id}/auth/oauth_providers/{oauth_provider_id}
	DeleteNeonAuthOauthProvider(ctx context.Context, params DeleteNeonAuthOauthProviderParams) error
	// DeleteNeonAuthUser implements deleteNeonAuthUser operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/users/{auth_user_id}` instead.
	// Deletes the auth user for the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// DELETE /projects/{project_id}/auth/users/{auth_user_id}
	DeleteNeonAuthUser(ctx context.Context, params DeleteNeonAuthUserParams) error
	// DeleteOrganizationVPCEndpoint implements deleteOrganizationVPCEndpoint operation.
	//
	// Deletes the VPC endpoint from the specified Neon organization.
	// If you delete a VPC endpoint from a Neon organization, that VPC endpoint cannot
	// be added back to the Neon organization.
	//
	// DELETE /organizations/{org_id}/vpc/region/{region_id}/vpc_endpoints/{vpc_endpoint_id}
	DeleteOrganizationVPCEndpoint(ctx context.Context, params DeleteOrganizationVPCEndpointParams) error
	// DeleteProject implements deleteProject operation.
	//
	// Deletes the specified project.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// Deleting a project is a permanent action.
	// Deleting a project also deletes endpoints, branches, databases, and users that belong to the
	// project.
	//
	// DELETE /projects/{project_id}
	DeleteProject(ctx context.Context, params DeleteProjectParams) (*ProjectResponse, error)
	// DeleteProjectBranch implements deleteProjectBranch operation.
	//
	// Deletes the specified branch from a project, and places
	// all compute endpoints into an idle state, breaking existing client connections.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain a `branch_id` by listing the project's branches.
	// For related information, see [Manage branches](https://neon.tech/docs/manage/branches/).
	// When a successful response status is received, the compute endpoints are still active,
	// and the branch is not yet deleted from storage.
	// The deletion occurs after all operations finish.
	// You cannot delete a project's root or default branch, and you cannot delete a branch that has a
	// child branch.
	// A project must have at least one branch.
	//
	// DELETE /projects/{project_id}/branches/{branch_id}
	DeleteProjectBranch(ctx context.Context, params DeleteProjectBranchParams) (DeleteProjectBranchRes, error)
	// DeleteProjectBranchDataAPI implements deleteProjectBranchDataAPI operation.
	//
	// Deletes the Neon Data API for the specified branch.
	// You can obtain the `project_id` and `branch_id` by listing the projects and branches for your Neon
	// account.
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/data-api/{database_name}
	DeleteProjectBranchDataAPI(ctx context.Context, params DeleteProjectBranchDataAPIParams) error
	// DeleteProjectBranchDatabase implements deleteProjectBranchDatabase operation.
	//
	// Deletes the specified database from the branch.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` and `database_name` by listing the branch's databases.
	// For related information, see [Manage databases](https://neon.tech/docs/manage/databases/).
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/databases/{database_name}
	DeleteProjectBranchDatabase(ctx context.Context, params DeleteProjectBranchDatabaseParams) (DeleteProjectBranchDatabaseRes, error)
	// DeleteProjectBranchRole implements deleteProjectBranchRole operation.
	//
	// Deletes the specified Postgres role from the branch.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` by listing the project's branches.
	// You can obtain the `role_name` by listing the roles for a branch.
	// For related information, see [Manage roles](https://neon.tech/docs/manage/roles/).
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/roles/{role_name}
	DeleteProjectBranchRole(ctx context.Context, params DeleteProjectBranchRoleParams) (DeleteProjectBranchRoleRes, error)
	// DeleteProjectEndpoint implements deleteProjectEndpoint operation.
	//
	// Delete the specified compute endpoint.
	// A compute endpoint is a Neon compute instance.
	// Deleting a compute endpoint drops existing network connections to the compute endpoint.
	// The deletion is completed when last operation in the chain finishes successfully.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain an `endpoint_id` by listing your project's compute endpoints.
	// An `endpoint_id` has an `ep-` prefix.
	// For information about compute endpoints, see [Manage computes](https://neon.
	// tech/docs/manage/endpoints/).
	//
	// DELETE /projects/{project_id}/endpoints/{endpoint_id}
	DeleteProjectEndpoint(ctx context.Context, params DeleteProjectEndpointParams) (DeleteProjectEndpointRes, error)
	// DeleteProjectJWKS implements deleteProjectJWKS operation.
	//
	// Deletes a JWKS URL from the specified project.
	//
	// DELETE /projects/{project_id}/jwks/{jwks_id}
	DeleteProjectJWKS(ctx context.Context, params DeleteProjectJWKSParams) (*JWKS, error)
	// DeleteProjectVPCEndpoint implements deleteProjectVPCEndpoint operation.
	//
	// Removes the specified VPC endpoint restriction from a Neon project.
	//
	// DELETE /projects/{project_id}/vpc_endpoints/{vpc_endpoint_id}
	DeleteProjectVPCEndpoint(ctx context.Context, params DeleteProjectVPCEndpointParams) error
	// DeleteSnapshot implements deleteSnapshot operation.
	//
	// Delete the specified snapshot.
	// **Note**: This endpoint is currently in Beta.
	//
	// DELETE /projects/{project_id}/snapshots/{snapshot_id}
	DeleteSnapshot(ctx context.Context, params DeleteSnapshotParams) (*OperationsResponse, error)
	// DisableNeonAuth implements disableNeonAuth operation.
	//
	// Disables Neon Auth for the branch.
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/auth
	DisableNeonAuth(ctx context.Context, req OptDisableNeonAuthReq, params DisableNeonAuthParams) error
	// FinalizeRestoreBranch implements finalizeRestoreBranch operation.
	//
	// Finalize the restore operation for a branch created from a snapshot.
	// This operation updates the branch so it functions as the original branch it replaced.
	// This includes:
	// - Reassigning any computes from the original branch to the restored branch (this will restart the
	// computes)
	// - Renaming the restored branch to the original branch's name
	// - Renaming the original branch so it no longer uses the original name
	// This operation only applies to branches created using the `restoreSnapshot` endpoint with
	// `finalize_restore: false`.
	// **Note**: This endpoint is currently in Beta.
	//
	// POST /projects/{project_id}/branches/{branch_id}/finalize_restore
	FinalizeRestoreBranch(ctx context.Context, req OptFinalizeRestoreBranchReq, params FinalizeRestoreBranchParams) (*OperationsResponse, error)
	// GetActiveRegions implements getActiveRegions operation.
	//
	// Lists supported Neon regions.
	// **Note:** Not all regions are available to all organizations. Pass the `org_id`
	// parameter to get an accurate list of regions available to your organization.
	//
	// GET /regions
	GetActiveRegions(ctx context.Context, params GetActiveRegionsParams) (*ActiveRegionsResponse, error)
	// GetAnonymizedBranchStatus implements getAnonymizedBranchStatus operation.
	//
	// Retrieves the current status of an anonymized branch, including its state and progress information.
	// This endpoint allows you to monitor the anonymization process from initialization through
	// completion.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` by listing the project's branches.
	// Only anonymized branches will have status information available.
	// **Note**: This endpoint is currently in Beta.
	//
	// GET /projects/{project_id}/branches/{branch_id}/anonymized_status
	GetAnonymizedBranchStatus(ctx context.Context, params GetAnonymizedBranchStatusParams) (*AnonymizedBranchStatusResponse, error)
	// GetAuthDetails implements getAuthDetails operation.
	//
	// Returns auth information about the passed credentials. It can refer to an API key, Bearer token or
	// OAuth session.
	//
	// GET /auth
	GetAuthDetails(ctx context.Context) (*AuthDetailsResponse, error)
	// GetAvailablePreloadLibraries implements getAvailablePreloadLibraries operation.
	//
	// Return available shared preload libraries.
	//
	// GET /projects/{project_id}/available_preload_libraries
	GetAvailablePreloadLibraries(ctx context.Context, params GetAvailablePreloadLibrariesParams) (*AvailablePreloadLibraries, error)
	// GetConnectionURI implements getConnectionURI operation.
	//
	// Retrieves a connection URI for the specified database.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `database_name` by listing the databases for a branch.
	// You can obtain a `role_name` by listing the roles for a branch.
	//
	// GET /projects/{project_id}/connection_uri
	GetConnectionURI(ctx context.Context, params GetConnectionURIParams) (*ConnectionURIResponse, error)
	// GetConsumptionHistoryPerAccount implements getConsumptionHistoryPerAccount operation.
	//
	// Retrieves consumption metrics for Scale and Enterprise plan accounts, and for legacy Scale,
	// Business, and Enterprise plan accounts.
	// Consumption history begins at the time the account was upgraded to a supported plan.
	// **Deprecated**: This endpoint will be removed on June 1, 2026.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /consumption_history/account
	GetConsumptionHistoryPerAccount(ctx context.Context, params GetConsumptionHistoryPerAccountParams) (GetConsumptionHistoryPerAccountRes, error)
	// GetConsumptionHistoryPerProject implements getConsumptionHistoryPerProject operation.
	//
	// Retrieves consumption metrics for Scale, Business, and Enterprise plan projects. History begins at
	// the time of upgrade.
	// Results are ordered by time in ascending order (oldest to newest).
	// Issuing a call to this API does not wake a project's compute endpoint.
	//
	// GET /consumption_history/projects
	GetConsumptionHistoryPerProject(ctx context.Context, params GetConsumptionHistoryPerProjectParams) (GetConsumptionHistoryPerProjectRes, error)
	// GetConsumptionHistoryPerProjectV2 implements getConsumptionHistoryPerProjectV2 operation.
	//
	// Retrieves consumption metrics for Launch, Scale, Agent, and Enterprise plan projects. History
	// begins at the time of upgrade.
	// Results are ordered by time in ascending order (oldest to newest).
	// Issuing a call to this API does not wake a project's compute endpoint.
	//
	// GET /consumption_history/v2/projects
	GetConsumptionHistoryPerProjectV2(ctx context.Context, params GetConsumptionHistoryPerProjectV2Params) (GetConsumptionHistoryPerProjectV2Res, error)
	// GetCurrentUserInfo implements getCurrentUserInfo operation.
	//
	// Retrieves information about the current Neon user account.
	//
	// GET /users/me
	GetCurrentUserInfo(ctx context.Context) (*CurrentUserInfoResponse, error)
	// GetCurrentUserOrganizations implements getCurrentUserOrganizations operation.
	//
	// Retrieves information about the current Neon user's organizations.
	//
	// GET /users/me/organizations
	GetCurrentUserOrganizations(ctx context.Context) (*OrganizationsResponse, error)
	// GetMaskingRules implements getMaskingRules operation.
	//
	// Retrieves the masking rules for the specified anonymized branch.
	// Masking rules define how sensitive data should be anonymized using PostgreSQL Anonymizer.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` by listing the project's branches.
	// **Note**: This endpoint is currently in Beta.
	//
	// GET /projects/{project_id}/branches/{branch_id}/masking_rules
	GetMaskingRules(ctx context.Context, params GetMaskingRulesParams) (*MaskingRulesResponse, error)
	// GetNeonAuth implements getNeonAuth operation.
	//
	// / Fetches the details of the Neon Auth for the specified branch. You can obtain the `project_id`
	// and `branch_id` by listing the projects and branches for your Neon account.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth
	GetNeonAuth(ctx context.Context, params GetNeonAuthParams) (*NeonAuthIntegration, error)
	// GetNeonAuthAllowLocalhost implements getNeonAuthAllowLocalhost operation.
	//
	// Get the allow localhost configuration for the specified branch.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth/allow_localhost
	GetNeonAuthAllowLocalhost(ctx context.Context, params GetNeonAuthAllowLocalhostParams) (*NeonAuthAllowLocalhostResponse, error)
	// GetNeonAuthEmailAndPasswordConfig implements getNeonAuthEmailAndPasswordConfig operation.
	//
	// Gets the email and password authentication configuration for Neon Auth.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth/email_and_password
	GetNeonAuthEmailAndPasswordConfig(ctx context.Context, params GetNeonAuthEmailAndPasswordConfigParams) (*NeonAuthEmailAndPasswordConfig, error)
	// GetNeonAuthEmailProvider implements getNeonAuthEmailProvider operation.
	//
	// Gets the email provider configuration for the specified branch.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth/email_provider
	GetNeonAuthEmailProvider(ctx context.Context, params GetNeonAuthEmailProviderParams) (*NeonAuthEmailServerConfig, error)
	// GetNeonAuthEmailServer implements getNeonAuthEmailServer operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/email_provider` instead. Gets
	// the email server configuration for the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /projects/{project_id}/auth/email_server
	GetNeonAuthEmailServer(ctx context.Context, params GetNeonAuthEmailServerParams) (*NeonAuthEmailServerConfig, error)
	// GetNeonAuthPhoneNumberPlugin implements getNeonAuthPhoneNumberPlugin operation.
	//
	// Returns the phone number plugin configuration for Neon Auth.
	// The phone number plugin enables phone-based OTP authentication.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth/plugins/phone_number
	GetNeonAuthPhoneNumberPlugin(ctx context.Context, params GetNeonAuthPhoneNumberPluginParams) (*NeonAuthPhoneNumberConfig, error)
	// GetNeonAuthPluginConfigs implements getNeonAuthPluginConfigs operation.
	//
	// Returns all plugin configurations for Neon Auth in a single response.
	// This endpoint aggregates organization, email provider, email and password,
	// OAuth providers, and localhost settings.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth/plugins
	GetNeonAuthPluginConfigs(ctx context.Context, params GetNeonAuthPluginConfigsParams) (*NeonAuthPluginConfigs, error)
	// GetNeonAuthWebhookConfig implements getNeonAuthWebhookConfig operation.
	//
	// Returns the webhook configuration for Neon Auth.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth/webhooks
	GetNeonAuthWebhookConfig(ctx context.Context, params GetNeonAuthWebhookConfigParams) (*NeonAuthWebhookConfig, error)
	// GetOrganization implements getOrganization operation.
	//
	// Retrieves information about the specified organization.
	//
	// GET /organizations/{org_id}
	GetOrganization(ctx context.Context, params GetOrganizationParams) (*Organization, error)
	// GetOrganizationInvitations implements getOrganizationInvitations operation.
	//
	// Retrieves information about extended invitations for the specified organization.
	//
	// GET /organizations/{org_id}/invitations
	GetOrganizationInvitations(ctx context.Context, params GetOrganizationInvitationsParams) (*OrganizationInvitationsResponse, error)
	// GetOrganizationMember implements getOrganizationMember operation.
	//
	// Retrieves information about the specified organization member.
	//
	// GET /organizations/{org_id}/members/{member_id}
	GetOrganizationMember(ctx context.Context, params GetOrganizationMemberParams) (*Member, error)
	// GetOrganizationMembers implements getOrganizationMembers operation.
	//
	// Retrieves a paginated list of members for the specified organization.
	//
	// GET /organizations/{org_id}/members
	GetOrganizationMembers(ctx context.Context, params GetOrganizationMembersParams) (*GetOrganizationMembersOK, error)
	// GetOrganizationVPCEndpointDetails implements getOrganizationVPCEndpointDetails operation.
	//
	// Retrieves the current state and configuration details of a specified VPC endpoint.
	//
	// GET /organizations/{org_id}/vpc/region/{region_id}/vpc_endpoints/{vpc_endpoint_id}
	GetOrganizationVPCEndpointDetails(ctx context.Context, params GetOrganizationVPCEndpointDetailsParams) (*VPCEndpointDetails, error)
	// GetProject implements getProject operation.
	//
	// Retrieves information about the specified project.
	// You can obtain a `project_id` by listing the projects for an organization.
	//
	// GET /projects/{project_id}
	GetProject(ctx context.Context, params GetProjectParams) (*ProjectResponse, error)
	// GetProjectAdvisorSecurityIssues implements getProjectAdvisorSecurityIssues operation.
	//
	// Analyzes the database for security and performance issues.
	// Returns a list of issues categorized by severity (ERROR, WARN, INFO).
	// Requires read access to the project and Data API enabled.
	//
	// GET /projects/{project_id}/advisors
	GetProjectAdvisorSecurityIssues(ctx context.Context, params GetProjectAdvisorSecurityIssuesParams) (*GetProjectAdvisorSecurityIssuesOK, error)
	// GetProjectBranch implements getProjectBranch operation.
	//
	// Retrieves information about the specified branch.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain a `branch_id` by listing the project's branches.
	// A `branch_id` value has a `br-` prefix.
	// Each Neon project is initially created with a root and default branch named `main`.
	// A project can contain one or more branches.
	// A parent branch is identified by a `parent_id` value, which is the `id` of the parent branch.
	// For related information, see [Manage branches](https://neon.tech/docs/manage/branches/).
	//
	// GET /projects/{project_id}/branches/{branch_id}
	GetProjectBranch(ctx context.Context, params GetProjectBranchParams) (*GetProjectBranchOK, error)
	// GetProjectBranchDataAPI implements getProjectBranchDataAPI operation.
	//
	// Retrieves the Neon Data API for the specified branch.
	//
	// GET /projects/{project_id}/branches/{branch_id}/data-api/{database_name}
	GetProjectBranchDataAPI(ctx context.Context, params GetProjectBranchDataAPIParams) (*DataAPIReponse, error)
	// GetProjectBranchDatabase implements getProjectBranchDatabase operation.
	//
	// Retrieves information about the specified database.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` and `database_name` by listing the branch's databases.
	// For related information, see [Manage databases](https://neon.tech/docs/manage/databases/).
	//
	// GET /projects/{project_id}/branches/{branch_id}/databases/{database_name}
	GetProjectBranchDatabase(ctx context.Context, params GetProjectBranchDatabaseParams) (*DatabaseResponse, error)
	// GetProjectBranchRole implements getProjectBranchRole operation.
	//
	// Retrieves details about the specified role.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` by listing the project's branches.
	// You can obtain the `role_name` by listing the roles for a branch.
	// In Neon, the terms "role" and "user" are synonymous.
	// For related information, see [Manage roles](https://neon.tech/docs/manage/roles/).
	//
	// GET /projects/{project_id}/branches/{branch_id}/roles/{role_name}
	GetProjectBranchRole(ctx context.Context, params GetProjectBranchRoleParams) (*RoleResponse, error)
	// GetProjectBranchRolePassword implements getProjectBranchRolePassword operation.
	//
	// Retrieves the password for the specified Postgres role, if possible.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` by listing the project's branches.
	// You can obtain the `role_name` by listing the roles for a branch.
	// For related information, see [Manage roles](https://neon.tech/docs/manage/roles/).
	//
	// GET /projects/{project_id}/branches/{branch_id}/roles/{role_name}/reveal_password
	GetProjectBranchRolePassword(ctx context.Context, params GetProjectBranchRolePasswordParams) (GetProjectBranchRolePasswordRes, error)
	// GetProjectBranchSchema implements getProjectBranchSchema operation.
	//
	// Retrieves the schema from the specified database. The `lsn` and `timestamp` values cannot be
	// specified at the same time. If both are omitted, the database schema is retrieved from database's
	// head.
	//
	// GET /projects/{project_id}/branches/{branch_id}/schema
	GetProjectBranchSchema(ctx context.Context, params GetProjectBranchSchemaParams) (*BranchSchemaResponse, error)
	// GetProjectBranchSchemaComparison implements getProjectBranchSchemaComparison operation.
	//
	// Compares the schema from the specified database with another branch's schema.
	//
	// GET /projects/{project_id}/branches/{branch_id}/compare_schema
	GetProjectBranchSchemaComparison(ctx context.Context, params GetProjectBranchSchemaComparisonParams) (*BranchSchemaCompareResponse, error)
	// GetProjectEndpoint implements getProjectEndpoint operation.
	//
	// Retrieves information about the specified compute endpoint.
	// A compute endpoint is a Neon compute instance.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain an `endpoint_id` by listing your project's compute endpoints.
	// An `endpoint_id` has an `ep-` prefix.
	// For information about compute endpoints, see [Manage computes](https://neon.
	// tech/docs/manage/endpoints/).
	//
	// GET /projects/{project_id}/endpoints/{endpoint_id}
	GetProjectEndpoint(ctx context.Context, params GetProjectEndpointParams) (*EndpointResponse, error)
	// GetProjectJWKS implements getProjectJWKS operation.
	//
	// Returns the JWKS URLs available for verifying JWTs used as the authentication mechanism for the
	// specified project.
	//
	// GET /projects/{project_id}/jwks
	GetProjectJWKS(ctx context.Context, params GetProjectJWKSParams) (*ProjectJWKSResponse, error)
	// GetProjectOperation implements getProjectOperation operation.
	//
	// Retrieves details for the specified operation.
	// An operation is an action performed on a Neon project resource.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain a `operation_id` by listing operations for the project.
	//
	// GET /projects/{project_id}/operations/{operation_id}
	GetProjectOperation(ctx context.Context, params GetProjectOperationParams) (*OperationResponse, error)
	// GetSnapshotSchedule implements getSnapshotSchedule operation.
	//
	// View the backup schedule for the specified branch.
	// **Note**: This endpoint is currently in Beta.
	//
	// GET /projects/{project_id}/branches/{branch_id}/backup_schedule
	GetSnapshotSchedule(ctx context.Context, params GetSnapshotScheduleParams) (*BackupSchedule, error)
	// GrantPermissionToProject implements grantPermissionToProject operation.
	//
	// Grants project access to the account associated with the specified email address.
	//
	// POST /projects/{project_id}/permissions
	GrantPermissionToProject(ctx context.Context, req *GrantPermissionToProjectRequest, params GrantPermissionToProjectParams) (*ProjectPermission, error)
	// ListApiKeys implements listApiKeys operation.
	//
	// Retrieves the API keys for your Neon account.
	// The response does not include API key tokens. A token is only provided when creating an API key.
	// API keys can also be managed in the Neon Console.
	// For more information, see [Manage API keys](https://neon.tech/docs/manage/api-keys/).
	//
	// GET /api_keys
	ListApiKeys(ctx context.Context) ([]ApiKeysListResponseItem, error)
	// ListBranchNeonAuthOauthProviders implements listBranchNeonAuthOauthProviders operation.
	//
	// Lists the OAuth providers for the specified project and branch.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth/oauth_providers
	ListBranchNeonAuthOauthProviders(ctx context.Context, params ListBranchNeonAuthOauthProvidersParams) (*ListNeonAuthOauthProvidersResponse, error)
	// ListBranchNeonAuthTrustedDomains implements listBranchNeonAuthTrustedDomains operation.
	//
	// Lists the domains in the redirect_uri whitelist for the specified project.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth/domains
	ListBranchNeonAuthTrustedDomains(ctx context.Context, params ListBranchNeonAuthTrustedDomainsParams) (*NeonAuthRedirectURIWhitelistResponse, error)
	// ListNeonAuthIntegrations implements listNeonAuthIntegrations operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth` instead.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /projects/{project_id}/auth/integrations
	ListNeonAuthIntegrations(ctx context.Context, params ListNeonAuthIntegrationsParams) (*ListNeonAuthIntegrationsResponse, error)
	// ListNeonAuthOauthProviders implements listNeonAuthOauthProviders operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/oauth_providers` instead. Lists
	// the OAuth providers for the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /projects/{project_id}/auth/oauth_providers
	ListNeonAuthOauthProviders(ctx context.Context, params ListNeonAuthOauthProvidersParams) (*ListNeonAuthOauthProvidersResponse, error)
	// ListNeonAuthRedirectURIWhitelistDomains implements listNeonAuthRedirectURIWhitelistDomains operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/domains` instead. Lists the
	// domains in the redirect_uri whitelist for the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /projects/{project_id}/auth/domains
	ListNeonAuthRedirectURIWhitelistDomains(ctx context.Context, params ListNeonAuthRedirectURIWhitelistDomainsParams) (*NeonAuthRedirectURIWhitelistResponse, error)
	// ListOrgApiKeys implements listOrgApiKeys operation.
	//
	// Retrieves the API keys for the specified organization.
	// The response does not include API key tokens. A token is only provided when creating an API key.
	// API keys can also be managed in the Neon Console.
	// For more information, see [Manage API keys](https://neon.tech/docs/manage/api-keys/).
	//
	// GET /organizations/{org_id}/api_keys
	ListOrgApiKeys(ctx context.Context, params ListOrgApiKeysParams) ([]OrgApiKeysListResponseItem, error)
	// ListOrganizationVPCEndpoints implements listOrganizationVPCEndpoints operation.
	//
	// Retrieves the list of VPC endpoints for the specified Neon organization.
	//
	// GET /organizations/{org_id}/vpc/region/{region_id}/vpc_endpoints
	ListOrganizationVPCEndpoints(ctx context.Context, params ListOrganizationVPCEndpointsParams) (*VPCEndpointsResponse, error)
	// ListOrganizationVPCEndpointsAllRegions implements listOrganizationVPCEndpointsAllRegions operation.
	//
	// Retrieves the list of VPC endpoints for the specified Neon organization across all regions.
	//
	// GET /organizations/{org_id}/vpc/vpc_endpoints
	ListOrganizationVPCEndpointsAllRegions(ctx context.Context, params ListOrganizationVPCEndpointsAllRegionsParams) (*VPCEndpointsWithRegionResponse, error)
	// ListProjectBranchDatabases implements listProjectBranchDatabases operation.
	//
	// Retrieves a list of databases for the specified branch.
	// A branch can have multiple databases.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` by listing the project's branches.
	// For related information, see [Manage databases](https://neon.tech/docs/manage/databases/).
	//
	// GET /projects/{project_id}/branches/{branch_id}/databases
	ListProjectBranchDatabases(ctx context.Context, params ListProjectBranchDatabasesParams) (*DatabasesResponse, error)
	// ListProjectBranchEndpoints implements listProjectBranchEndpoints operation.
	//
	// Retrieves a list of compute endpoints for the specified branch.
	// Neon permits only one read-write compute endpoint per branch.
	// A branch can have multiple read-only compute endpoints.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` by listing the project's branches.
	//
	// GET /projects/{project_id}/branches/{branch_id}/endpoints
	ListProjectBranchEndpoints(ctx context.Context, params ListProjectBranchEndpointsParams) (*EndpointsResponse, error)
	// ListProjectBranchRoles implements listProjectBranchRoles operation.
	//
	// Retrieves a list of Postgres roles from the specified branch.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` by listing the project's branches.
	// For related information, see [Manage roles](https://neon.tech/docs/manage/roles/).
	//
	// GET /projects/{project_id}/branches/{branch_id}/roles
	ListProjectBranchRoles(ctx context.Context, params ListProjectBranchRolesParams) (*RolesResponse, error)
	// ListProjectBranches implements listProjectBranches operation.
	//
	// Retrieves a list of branches for the specified project.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// Each Neon project has a root branch named `main`.
	// A `branch_id` value has a `br-` prefix.
	// A project may contain child branches that were branched from `main` or from another branch.
	// A parent branch is identified by the `parent_id` value, which is the `id` of the parent branch.
	// For related information, see [Manage branches](https://neon.tech/docs/manage/branches/).
	//
	// GET /projects/{project_id}/branches
	ListProjectBranches(ctx context.Context, params ListProjectBranchesParams) (*ListProjectBranchesOK, error)
	// ListProjectEndpoints implements listProjectEndpoints operation.
	//
	// Retrieves a list of compute endpoints for the specified project.
	// A compute endpoint is a Neon compute instance.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// For information about compute endpoints, see [Manage computes](https://neon.
	// tech/docs/manage/endpoints/).
	//
	// GET /projects/{project_id}/endpoints
	ListProjectEndpoints(ctx context.Context, params ListProjectEndpointsParams) (*EndpointsResponse, error)
	// ListProjectOperations implements listProjectOperations operation.
	//
	// Retrieves a list of operations for the specified Neon project.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// The number of operations returned can be large.
	// To paginate the response, issue an initial request with a `limit` value.
	// Then, add the `cursor` value that was returned in the response to the next request.
	// Operations older than 6 months may be deleted from our systems.
	// If you need more history than that, you should store your own history.
	//
	// GET /projects/{project_id}/operations
	ListProjectOperations(ctx context.Context, params ListProjectOperationsParams) (*ListOperations, error)
	// ListProjectPermissions implements listProjectPermissions operation.
	//
	// Retrieves details about users who have access to the project, including the permission `id`, the
	// granted-to email address, and the date project access was granted.
	//
	// GET /projects/{project_id}/permissions
	ListProjectPermissions(ctx context.Context, params ListProjectPermissionsParams) (*ProjectPermissions, error)
	// ListProjectVPCEndpoints implements listProjectVPCEndpoints operation.
	//
	// Lists VPC endpoint restrictions for the specified Neon project.
	//
	// GET /projects/{project_id}/vpc_endpoints
	ListProjectVPCEndpoints(ctx context.Context, params ListProjectVPCEndpointsParams) (*VPCEndpointsResponse, error)
	// ListProjects implements listProjects operation.
	//
	// Retrieves a list of projects for an organization.
	// You may need to specify an org_id parameter depending on your API key type.
	// For more information, see [Manage projects](https://neon.tech/docs/manage/projects/).
	//
	// GET /projects
	ListProjects(ctx context.Context, params ListProjectsParams) (*ListProjectsOK, error)
	// ListSharedProjects implements listSharedProjects operation.
	//
	// Retrieves a list of projects shared with your Neon account.
	// For more information, see [Manage projects](https://neon.tech/docs/manage/projects/).
	//
	// GET /projects/shared
	ListSharedProjects(ctx context.Context, params ListSharedProjectsParams) (*ListSharedProjectsOK, error)
	// ListSnapshots implements listSnapshots operation.
	//
	// List the snapshots for the specified project.
	// **Note**: This endpoint is currently in Beta.
	//
	// GET /projects/{project_id}/snapshots
	ListSnapshots(ctx context.Context, params ListSnapshotsParams) (*ListSnapshotsOK, error)
	// RecoverProject implements recoverProject operation.
	//
	// Recovers a deleted project during the deletion grace period.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	//
	// POST /projects/{project_id}/recover
	RecoverProject(ctx context.Context, params RecoverProjectParams) (*ProjectRecoverResponse, error)
	// RemoveOrganizationMember implements removeOrganizationMember operation.
	//
	// Remove member from the organization.
	// Only an admin of the organization can perform this action.
	// If another admin is being removed, it will not be allows in case it is the only admin left in the
	// organization.
	//
	// DELETE /organizations/{org_id}/members/{member_id}
	RemoveOrganizationMember(ctx context.Context, params RemoveOrganizationMemberParams) error
	// ResetProjectBranchRolePassword implements resetProjectBranchRolePassword operation.
	//
	// Resets the password for the specified Postgres role.
	// Returns a new password and operations. The new password is ready to use when the last operation
	// finishes.
	// The old password remains valid until last operation finishes.
	// Connections to the compute endpoint are dropped. If idle,
	// the compute endpoint becomes active for a short period of time.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` by listing the project's branches.
	// You can obtain the `role_name` by listing the roles for a branch.
	// For related information, see [Manage roles](https://neon.tech/docs/manage/roles/).
	//
	// POST /projects/{project_id}/branches/{branch_id}/roles/{role_name}/reset_password
	ResetProjectBranchRolePassword(ctx context.Context, params ResetProjectBranchRolePasswordParams) (*RoleOperations, error)
	// RestartProjectEndpoint implements restartProjectEndpoint operation.
	//
	// Restart the specified compute endpoint: suspend immediately followed by start operations.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain an `endpoint_id` by listing your project's compute endpoints.
	// An `endpoint_id` has an `ep-` prefix.
	// For information about compute endpoints, see [Manage computes](https://neon.
	// tech/docs/manage/endpoints/).
	//
	// POST /projects/{project_id}/endpoints/{endpoint_id}/restart
	RestartProjectEndpoint(ctx context.Context, params RestartProjectEndpointParams) (*EndpointOperations, error)
	// RestoreProject implements restoreProject operation.
	//
	// DEPRECATED, use `/projects/{project_id}/recover` instead. Restores a deleted project during the
	// deletion grace period.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /projects/{project_id}/restore
	RestoreProject(ctx context.Context, params RestoreProjectParams) (*ProjectRecoverResponse, error)
	// RestoreProjectBranch implements restoreProjectBranch operation.
	//
	// Restores a branch to an earlier state in its own or another branch's history.
	//
	// POST /projects/{project_id}/branches/{branch_id}/restore
	RestoreProjectBranch(ctx context.Context, req *BranchRestoreRequest, params RestoreProjectBranchParams) (*BranchOperations, error)
	// RestoreSnapshot implements restoreSnapshot operation.
	//
	// Restore the specified snapshot to a new branch and optionally finalize the restore operation.
	// **Note**: This endpoint is currently in Beta.
	//
	// POST /projects/{project_id}/snapshots/{snapshot_id}/restore
	RestoreSnapshot(ctx context.Context, req OptRestoreSnapshotReq, params RestoreSnapshotParams) (*RestoredSnapshot, error)
	// RevokeApiKey implements revokeApiKey operation.
	//
	// Revokes the specified API key.
	// An API key that is no longer needed can be revoked.
	// This action cannot be reversed.
	// You can obtain `key_id` values by listing the API keys for your Neon account.
	// API keys can also be managed in the Neon Console.
	// See [Manage API keys](https://neon.tech/docs/manage/api-keys/).
	//
	// DELETE /api_keys/{key_id}
	RevokeApiKey(ctx context.Context, params RevokeApiKeyParams) (*ApiKeyRevokeResponse, error)
	// RevokeOrgApiKey implements revokeOrgApiKey operation.
	//
	// Revokes the specified organization API key.
	// An API key that is no longer needed can be revoked.
	// This action cannot be reversed.
	// You can obtain `key_id` values by listing the API keys for an organization.
	// API keys can also be managed in the Neon Console.
	// See [Manage API keys](https://neon.tech/docs/manage/api-keys/).
	//
	// DELETE /organizations/{org_id}/api_keys/{key_id}
	RevokeOrgApiKey(ctx context.Context, params RevokeOrgApiKeyParams) (*OrgApiKeyRevokeResponse, error)
	// RevokePermissionFromProject implements revokePermissionFromProject operation.
	//
	// Revokes project access from the user associated with the specified permission `id`. You can
	// retrieve a user's permission `id` by listing project access.
	//
	// DELETE /projects/{project_id}/permissions/{permission_id}
	RevokePermissionFromProject(ctx context.Context, params RevokePermissionFromProjectParams) (*ProjectPermission, error)
	// SendNeonAuthTestEmail implements sendNeonAuthTestEmail operation.
	//
	// Sends a test email to the specified email address.
	//
	// POST /projects/{project_id}/branches/{branch_id}/auth/send_test_email
	SendNeonAuthTestEmail(ctx context.Context, req *SendNeonAuthTestEmailRequest, params SendNeonAuthTestEmailParams) (*SendNeonAuthTestEmailResponse, error)
	// SetDefaultProjectBranch implements setDefaultProjectBranch operation.
	//
	// Sets the specified branch as the project's default branch.
	// The default designation is automatically removed from the previous default branch.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` by listing the project's branches.
	// For more information, see [Manage branches](https://neon.tech/docs/manage/branches/).
	//
	// POST /projects/{project_id}/branches/{branch_id}/set_as_default
	SetDefaultProjectBranch(ctx context.Context, params SetDefaultProjectBranchParams) (*BranchOperations, error)
	// SetSnapshotSchedule implements setSnapshotSchedule operation.
	//
	// Update the backup schedule for the specified branch.
	// **Note** : This endpoint is currently in Beta.
	//
	// PUT /projects/{project_id}/branches/{branch_id}/backup_schedule
	SetSnapshotSchedule(ctx context.Context, req *BackupSchedule, params SetSnapshotScheduleParams) error
	// StartAnonymization implements startAnonymization operation.
	//
	// Starts the anonymization process for an anonymized branch that is in the initialized, error, or
	// anonymized state.
	// This will apply all defined masking rules to anonymize sensitive data in the branch databases.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` by listing the project's branches.
	// The branch must be an anonymized branch to start anonymization.
	// **Note**: This endpoint is currently in Beta.
	//
	// POST /projects/{project_id}/branches/{branch_id}/anonymize
	StartAnonymization(ctx context.Context, params StartAnonymizationParams) (*AnonymizedBranchStatusResponse, error)
	// StartProjectEndpoint implements startProjectEndpoint operation.
	//
	// Starts a compute endpoint. The compute endpoint is ready to use
	// after the last operation in chain finishes successfully.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain an `endpoint_id` by listing your project's compute endpoints.
	// An `endpoint_id` has an `ep-` prefix.
	// For information about compute endpoints, see [Manage computes](https://neon.
	// tech/docs/manage/endpoints/).
	//
	// POST /projects/{project_id}/endpoints/{endpoint_id}/start
	StartProjectEndpoint(ctx context.Context, params StartProjectEndpointParams) (*EndpointOperations, error)
	// SuspendProjectEndpoint implements suspendProjectEndpoint operation.
	//
	// Suspend the specified compute endpoint
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain an `endpoint_id` by listing your project's compute endpoints.
	// An `endpoint_id` has an `ep-` prefix.
	// For information about compute endpoints, see [Manage computes](https://neon.
	// tech/docs/manage/endpoints/).
	//
	// POST /projects/{project_id}/endpoints/{endpoint_id}/suspend
	SuspendProjectEndpoint(ctx context.Context, params SuspendProjectEndpointParams) (*EndpointOperations, error)
	// TransferNeonAuthProviderProject implements transferNeonAuthProviderProject operation.
	//
	// Transfer ownership of your Neon-managed auth project to your own auth provider account.
	//
	// POST /projects/auth/transfer_ownership
	TransferNeonAuthProviderProject(ctx context.Context, req *NeonAuthTransferAuthProviderProjectRequest) (*NeonAuthTransferAuthProviderProjectResponse, error)
	// TransferProjectsFromOrgToOrg implements transferProjectsFromOrgToOrg operation.
	//
	// Transfers selected projects, identified by their IDs, from your organization to another specified
	// organization.
	//
	// POST /organizations/{source_org_id}/projects/transfer
	TransferProjectsFromOrgToOrg(ctx context.Context, req *TransferProjectsToOrganizationRequest, params TransferProjectsFromOrgToOrgParams) (TransferProjectsFromOrgToOrgRes, error)
	// TransferProjectsFromUserToOrg implements transferProjectsFromUserToOrg operation.
	//
	// Transfers selected projects, identified by their IDs, from your personal account to a specified
	// organization.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /users/me/projects/transfer
	TransferProjectsFromUserToOrg(ctx context.Context, req *TransferProjectsToOrganizationRequest) (TransferProjectsFromUserToOrgRes, error)
	// UpdateBranchNeonAuthOauthProvider implements updateBranchNeonAuthOauthProvider operation.
	//
	// Updates a OAuth provider for the specified project.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/auth/oauth_providers/{oauth_provider_id}
	UpdateBranchNeonAuthOauthProvider(ctx context.Context, req *NeonAuthUpdateOAuthProviderRequest, params UpdateBranchNeonAuthOauthProviderParams) (*NeonAuthOauthProvider, error)
	// UpdateMaskingRules implements updateMaskingRules operation.
	//
	// Updates the masking rules for the specified anonymized branch.
	// Masking rules define how sensitive data should be anonymized using PostgreSQL Anonymizer.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` by listing the project's branches.
	// **Note**: This endpoint is currently in Beta.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/masking_rules
	UpdateMaskingRules(ctx context.Context, req *MaskingRulesUpdateRequest, params UpdateMaskingRulesParams) (*MaskingRulesResponse, error)
	// UpdateNeonAuthAllowLocalhost implements updateNeonAuthAllowLocalhost operation.
	//
	// Updates the allow localhost configuration for the specified branch.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/auth/allow_localhost
	UpdateNeonAuthAllowLocalhost(ctx context.Context, req *UpdateNeonAuthAllowLocalhostRequest, params UpdateNeonAuthAllowLocalhostParams) (*NeonAuthAllowLocalhostResponse, error)
	// UpdateNeonAuthConfig implements updateNeonAuthConfig operation.
	//
	// Updates the auth configuration for the branch.
	// Currently supports updating the application name used in auth emails.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/auth/config
	UpdateNeonAuthConfig(ctx context.Context, req *NeonAuthConfigUpdate, params UpdateNeonAuthConfigParams) (*NeonAuthConfigResponse, error)
	// UpdateNeonAuthEmailAndPasswordConfig implements updateNeonAuthEmailAndPasswordConfig operation.
	//
	// Updates the email and password authentication configuration for Neon Auth.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/auth/email_and_password
	UpdateNeonAuthEmailAndPasswordConfig(ctx context.Context, req *NeonAuthEmailAndPasswordConfigUpdate, params UpdateNeonAuthEmailAndPasswordConfigParams) (*NeonAuthEmailAndPasswordConfig, error)
	// UpdateNeonAuthEmailProvider implements updateNeonAuthEmailProvider operation.
	//
	// Updates the email provider configuration for the specified branch.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/auth/email_provider
	UpdateNeonAuthEmailProvider(ctx context.Context, req *NeonAuthEmailServerConfig, params UpdateNeonAuthEmailProviderParams) (*NeonAuthEmailServerConfig, error)
	// UpdateNeonAuthEmailServer implements updateNeonAuthEmailServer operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/email_provider` instead. Updates
	// the email server configuration for the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// PATCH /projects/{project_id}/auth/email_server
	UpdateNeonAuthEmailServer(ctx context.Context, req *NeonAuthEmailServerConfig, params UpdateNeonAuthEmailServerParams) (*NeonAuthEmailServerConfig, error)
	// UpdateNeonAuthMagicLinkPlugin implements updateNeonAuthMagicLinkPlugin operation.
	//
	// Updates the magic link plugin configuration for Neon Auth.
	// The magic link plugin enables passwordless authentication via email magic links.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/auth/plugins/magic-link
	UpdateNeonAuthMagicLinkPlugin(ctx context.Context, req *NeonAuthMagicLinkConfigUpdate, params UpdateNeonAuthMagicLinkPluginParams) (*NeonAuthMagicLinkConfig, error)
	// UpdateNeonAuthOauthProvider implements updateNeonAuthOauthProvider operation.
	//
	// DEPRECATED, use
	// `/projects/{project_id}/branches/{branch_id}/auth/oauth_providers/{oauth_provider_id}` instead.
	// Updates a OAuth provider for the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// PATCH /projects/{project_id}/auth/oauth_providers/{oauth_provider_id}
	UpdateNeonAuthOauthProvider(ctx context.Context, req *NeonAuthUpdateOAuthProviderRequest, params UpdateNeonAuthOauthProviderParams) (*NeonAuthOauthProvider, error)
	// UpdateNeonAuthOrganizationPlugin implements updateNeonAuthOrganizationPlugin operation.
	//
	// Updates the organization plugin configuration for Neon Auth.
	// The organization plugin enables multi-tenant organization support.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/auth/plugins/organization
	UpdateNeonAuthOrganizationPlugin(ctx context.Context, req *NeonAuthOrganizationConfigUpdate, params UpdateNeonAuthOrganizationPluginParams) (*NeonAuthOrganizationConfig, error)
	// UpdateNeonAuthPhoneNumberPlugin implements updateNeonAuthPhoneNumberPlugin operation.
	//
	// Updates the phone number plugin configuration for Neon Auth.
	// The phone number plugin enables phone-based OTP authentication.
	// OTP codes are delivered via the `send.otp` webhook event with `delivery_preference: "sms"`.
	// A webhook must be configured with the `send.otp` event enabled for SMS delivery to work.
	//
	// PUT /projects/{project_id}/branches/{branch_id}/auth/plugins/phone_number
	UpdateNeonAuthPhoneNumberPlugin(ctx context.Context, req *NeonAuthPhoneNumberConfig, params UpdateNeonAuthPhoneNumberPluginParams) (*NeonAuthPhoneNumberConfig, error)
	// UpdateNeonAuthUserRole implements updateNeonAuthUserRole operation.
	//
	// Updates the role of an auth user for the specified project.
	//
	// PUT /projects/{project_id}/branches/{branch_id}/auth/users/{auth_user_id}/role
	UpdateNeonAuthUserRole(ctx context.Context, req *UpdateNeonAuthUserRoleRequest, params UpdateNeonAuthUserRoleParams) (*UpdateNeonAuthUserRoleResponse, error)
	// UpdateNeonAuthWebhookConfig implements updateNeonAuthWebhookConfig operation.
	//
	// Updates the webhook configuration for Neon Auth on a specific branch.
	//
	// PUT /projects/{project_id}/branches/{branch_id}/auth/webhooks
	UpdateNeonAuthWebhookConfig(ctx context.Context, req *NeonAuthWebhookConfig, params UpdateNeonAuthWebhookConfigParams) (*NeonAuthWebhookConfig, error)
	// UpdateOrganizationMember implements updateOrganizationMember operation.
	//
	// Only an admin can perform this action.
	//
	// PATCH /organizations/{org_id}/members/{member_id}
	UpdateOrganizationMember(ctx context.Context, req *OrganizationMemberUpdateRequest, params UpdateOrganizationMemberParams) (*Member, error)
	// UpdateProject implements updateProject operation.
	//
	// Updates the specified project.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	//
	// PATCH /projects/{project_id}
	UpdateProject(ctx context.Context, req *ProjectUpdateRequest, params UpdateProjectParams) (*UpdateProjectOK, error)
	// UpdateProjectBranch implements updateProjectBranch operation.
	//
	// Updates the specified branch.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` by listing the project's branches.
	// For more information, see [Manage branches](https://neon.tech/docs/manage/branches/).
	//
	// PATCH /projects/{project_id}/branches/{branch_id}
	UpdateProjectBranch(ctx context.Context, req *BranchUpdateRequest, params UpdateProjectBranchParams) (*BranchOperations, error)
	// UpdateProjectBranchDataAPI implements updateProjectBranchDataAPI operation.
	//
	// Updates the Neon Data API configuration for the specified branch.
	// You can optionally provide settings to update the Data API configuration.
	// The schema cache is always refreshed as part of this operation.
	// You can obtain the `project_id` and `branch_id` by listing the projects and branches for your Neon
	// account.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/data-api/{database_name}
	UpdateProjectBranchDataAPI(ctx context.Context, req OptDataAPIUpdateRequest, params UpdateProjectBranchDataAPIParams) error
	// UpdateProjectBranchDatabase implements updateProjectBranchDatabase operation.
	//
	// Updates the specified database in the branch.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain the `branch_id` and `database_name` by listing the branch's databases.
	// For related information, see [Manage databases](https://neon.tech/docs/manage/databases/).
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/databases/{database_name}
	UpdateProjectBranchDatabase(ctx context.Context, req *DatabaseUpdateRequest, params UpdateProjectBranchDatabaseParams) (*DatabaseOperations, error)
	// UpdateProjectEndpoint implements updateProjectEndpoint operation.
	//
	// Updates the specified compute endpoint.
	// You can obtain a `project_id` by listing the projects for your Neon account.
	// You can obtain an `endpoint_id` and `branch_id` by listing your project's compute endpoints.
	// An `endpoint_id` has an `ep-` prefix. A `branch_id` has a `br-` prefix.
	// For more information about compute endpoints, see [Manage computes](https://neon.
	// tech/docs/manage/endpoints/).
	// If the returned list of operations is not empty, the compute endpoint is not ready to use.
	// The client must wait for the last operation to finish before using the compute endpoint.
	// If the compute endpoint was idle before the update, it becomes active for a short period of time,
	// and the control plane suspends it again after the update.
	//
	// PATCH /projects/{project_id}/endpoints/{endpoint_id}
	UpdateProjectEndpoint(ctx context.Context, req *EndpointUpdateRequest, params UpdateProjectEndpointParams) (*EndpointOperations, error)
	// UpdateSnapshot implements updateSnapshot operation.
	//
	// Update the specified snapshot.
	// **Note**: This endpoint is currently in Beta.
	//
	// PATCH /projects/{project_id}/snapshots/{snapshot_id}
	UpdateSnapshot(ctx context.Context, req *SnapshotUpdateRequest, params UpdateSnapshotParams) (*UpdateSnapshotOK, error)
	// NewError creates *GeneralErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GeneralErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
