// Code generated by ogen, DO NOT EDIT.

package neon

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBearerAuth handles BearerAuth security.
	// The Neon API requires an API key to authorize your requests, which you can enter below.
	// Refer to our documentation to find out how to generate and use [API keys](https://neon.
	// tech/docs/manage/api-keys).
	HandleBearerAuth(ctx context.Context, operationName OperationName, t BearerAuth) (context.Context, error)
	// HandleCookieAuth handles CookieAuth security.
	HandleCookieAuth(ctx context.Context, operationName OperationName, t CookieAuth) (context.Context, error)
	// HandleTokenCookieAuth handles TokenCookieAuth security.
	HandleTokenCookieAuth(ctx context.Context, operationName OperationName, t TokenCookieAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesBearerAuth is a private map storing roles per operation.
var operationRolesBearerAuth = map[string][]string{
	AcceptProjectTransferRequestOperation:                 []string{},
	AddBranchNeonAuthOauthProviderOperation:               []string{},
	AddBranchNeonAuthTrustedDomainOperation:               []string{},
	AddNeonAuthDomainToRedirectURIWhitelistOperation:      []string{},
	AddNeonAuthOauthProviderOperation:                     []string{},
	AddProjectJWKSOperation:                               []string{},
	AssignOrganizationVPCEndpointOperation:                []string{},
	AssignProjectVPCEndpointOperation:                     []string{},
	CountProjectBranchesOperation:                         []string{},
	CreateApiKeyOperation:                                 []string{},
	CreateBranchNeonAuthNewUserOperation:                  []string{},
	CreateNeonAuthOperation:                               []string{},
	CreateNeonAuthIntegrationOperation:                    []string{},
	CreateNeonAuthNewUserOperation:                        []string{},
	CreateNeonAuthProviderSDKKeysOperation:                []string{},
	CreateOrgApiKeyOperation:                              []string{},
	CreateOrganizationInvitationsOperation:                []string{},
	CreateProjectOperation:                                []string{},
	CreateProjectBranchOperation:                          []string{},
	CreateProjectBranchAnonymizedOperation:                []string{},
	CreateProjectBranchDataAPIOperation:                   []string{},
	CreateProjectBranchDatabaseOperation:                  []string{},
	CreateProjectBranchRoleOperation:                      []string{},
	CreateProjectEndpointOperation:                        []string{},
	CreateProjectTransferRequestOperation:                 []string{},
	CreateSnapshotOperation:                               []string{},
	DeleteBranchNeonAuthOauthProviderOperation:            []string{},
	DeleteBranchNeonAuthTrustedDomainOperation:            []string{},
	DeleteBranchNeonAuthUserOperation:                     []string{},
	DeleteNeonAuthDomainFromRedirectURIWhitelistOperation: []string{},
	DeleteNeonAuthIntegrationOperation:                    []string{},
	DeleteNeonAuthOauthProviderOperation:                  []string{},
	DeleteNeonAuthUserOperation:                           []string{},
	DeleteOrganizationVPCEndpointOperation:                []string{},
	DeleteProjectOperation:                                []string{},
	DeleteProjectBranchOperation:                          []string{},
	DeleteProjectBranchDataAPIOperation:                   []string{},
	DeleteProjectBranchDatabaseOperation:                  []string{},
	DeleteProjectBranchRoleOperation:                      []string{},
	DeleteProjectEndpointOperation:                        []string{},
	DeleteProjectJWKSOperation:                            []string{},
	DeleteProjectVPCEndpointOperation:                     []string{},
	DeleteSnapshotOperation:                               []string{},
	DisableNeonAuthOperation:                              []string{},
	FinalizeRestoreBranchOperation:                        []string{},
	GetActiveRegionsOperation:                             []string{},
	GetAnonymizedBranchStatusOperation:                    []string{},
	GetAuthDetailsOperation:                               []string{},
	GetAvailablePreloadLibrariesOperation:                 []string{},
	GetConnectionURIOperation:                             []string{},
	GetConsumptionHistoryPerAccountOperation:              []string{},
	GetConsumptionHistoryPerProjectOperation:              []string{},
	GetConsumptionHistoryPerProjectV2Operation:            []string{},
	GetCurrentUserInfoOperation:                           []string{},
	GetCurrentUserOrganizationsOperation:                  []string{},
	GetMaskingRulesOperation:                              []string{},
	GetNeonAuthOperation:                                  []string{},
	GetNeonAuthAllowLocalhostOperation:                    []string{},
	GetNeonAuthEmailAndPasswordConfigOperation:            []string{},
	GetNeonAuthEmailProviderOperation:                     []string{},
	GetNeonAuthEmailServerOperation:                       []string{},
	GetNeonAuthPluginConfigsOperation:                     []string{},
	GetNeonAuthWebhookConfigOperation:                     []string{},
	GetOrganizationOperation:                              []string{},
	GetOrganizationInvitationsOperation:                   []string{},
	GetOrganizationMemberOperation:                        []string{},
	GetOrganizationMembersOperation:                       []string{},
	GetOrganizationVPCEndpointDetailsOperation:            []string{},
	GetProjectOperation:                                   []string{},
	GetProjectAdvisorSecurityIssuesOperation:              []string{},
	GetProjectBranchOperation:                             []string{},
	GetProjectBranchDataAPIOperation:                      []string{},
	GetProjectBranchDatabaseOperation:                     []string{},
	GetProjectBranchRoleOperation:                         []string{},
	GetProjectBranchRolePasswordOperation:                 []string{},
	GetProjectBranchSchemaOperation:                       []string{},
	GetProjectBranchSchemaComparisonOperation:             []string{},
	GetProjectEndpointOperation:                           []string{},
	GetProjectJWKSOperation:                               []string{},
	GetProjectOperationOperation:                          []string{},
	GetSnapshotScheduleOperation:                          []string{},
	GrantPermissionToProjectOperation:                     []string{},
	ListApiKeysOperation:                                  []string{},
	ListBranchNeonAuthOauthProvidersOperation:             []string{},
	ListBranchNeonAuthTrustedDomainsOperation:             []string{},
	ListNeonAuthIntegrationsOperation:                     []string{},
	ListNeonAuthOauthProvidersOperation:                   []string{},
	ListNeonAuthRedirectURIWhitelistDomainsOperation:      []string{},
	ListOrgApiKeysOperation:                               []string{},
	ListOrganizationVPCEndpointsOperation:                 []string{},
	ListOrganizationVPCEndpointsAllRegionsOperation:       []string{},
	ListProjectBranchDatabasesOperation:                   []string{},
	ListProjectBranchEndpointsOperation:                   []string{},
	ListProjectBranchRolesOperation:                       []string{},
	ListProjectBranchesOperation:                          []string{},
	ListProjectEndpointsOperation:                         []string{},
	ListProjectOperationsOperation:                        []string{},
	ListProjectPermissionsOperation:                       []string{},
	ListProjectVPCEndpointsOperation:                      []string{},
	ListProjectsOperation:                                 []string{},
	ListSharedProjectsOperation:                           []string{},
	ListSnapshotsOperation:                                []string{},
	RecoverProjectOperation:                               []string{},
	RemoveOrganizationMemberOperation:                     []string{},
	ResetProjectBranchRolePasswordOperation:               []string{},
	RestartProjectEndpointOperation:                       []string{},
	RestoreProjectOperation:                               []string{},
	RestoreProjectBranchOperation:                         []string{},
	RestoreSnapshotOperation:                              []string{},
	RevokeApiKeyOperation:                                 []string{},
	RevokeOrgApiKeyOperation:                              []string{},
	RevokePermissionFromProjectOperation:                  []string{},
	SendNeonAuthTestEmailOperation:                        []string{},
	SetDefaultProjectBranchOperation:                      []string{},
	SetSnapshotScheduleOperation:                          []string{},
	StartAnonymizationOperation:                           []string{},
	StartProjectEndpointOperation:                         []string{},
	SuspendProjectEndpointOperation:                       []string{},
	TransferNeonAuthProviderProjectOperation:              []string{},
	TransferProjectsFromOrgToOrgOperation:                 []string{},
	TransferProjectsFromUserToOrgOperation:                []string{},
	UpdateBranchNeonAuthOauthProviderOperation:            []string{},
	UpdateMaskingRulesOperation:                           []string{},
	UpdateNeonAuthAllowLocalhostOperation:                 []string{},
	UpdateNeonAuthEmailAndPasswordConfigOperation:         []string{},
	UpdateNeonAuthEmailProviderOperation:                  []string{},
	UpdateNeonAuthEmailServerOperation:                    []string{},
	UpdateNeonAuthOauthProviderOperation:                  []string{},
	UpdateNeonAuthOrganizationPluginOperation:             []string{},
	UpdateNeonAuthUserRoleOperation:                       []string{},
	UpdateNeonAuthWebhookConfigOperation:                  []string{},
	UpdateOrganizationMemberOperation:                     []string{},
	UpdateProjectOperation:                                []string{},
	UpdateProjectBranchOperation:                          []string{},
	UpdateProjectBranchDataAPIOperation:                   []string{},
	UpdateProjectBranchDatabaseOperation:                  []string{},
	UpdateProjectEndpointOperation:                        []string{},
	UpdateSnapshotOperation:                               []string{},
}

// GetRolesForBearerAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerAuth(operation string) []string {
	roles, ok := operationRolesBearerAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesCookieAuth is a private map storing roles per operation.
var operationRolesCookieAuth = map[string][]string{
	AcceptProjectTransferRequestOperation:                 []string{},
	AddBranchNeonAuthOauthProviderOperation:               []string{},
	AddBranchNeonAuthTrustedDomainOperation:               []string{},
	AddNeonAuthDomainToRedirectURIWhitelistOperation:      []string{},
	AddNeonAuthOauthProviderOperation:                     []string{},
	AddProjectJWKSOperation:                               []string{},
	AssignOrganizationVPCEndpointOperation:                []string{},
	AssignProjectVPCEndpointOperation:                     []string{},
	CountProjectBranchesOperation:                         []string{},
	CreateApiKeyOperation:                                 []string{},
	CreateBranchNeonAuthNewUserOperation:                  []string{},
	CreateNeonAuthOperation:                               []string{},
	CreateNeonAuthIntegrationOperation:                    []string{},
	CreateNeonAuthNewUserOperation:                        []string{},
	CreateNeonAuthProviderSDKKeysOperation:                []string{},
	CreateOrgApiKeyOperation:                              []string{},
	CreateOrganizationInvitationsOperation:                []string{},
	CreateProjectOperation:                                []string{},
	CreateProjectBranchOperation:                          []string{},
	CreateProjectBranchAnonymizedOperation:                []string{},
	CreateProjectBranchDataAPIOperation:                   []string{},
	CreateProjectBranchDatabaseOperation:                  []string{},
	CreateProjectBranchRoleOperation:                      []string{},
	CreateProjectEndpointOperation:                        []string{},
	CreateProjectTransferRequestOperation:                 []string{},
	CreateSnapshotOperation:                               []string{},
	DeleteBranchNeonAuthOauthProviderOperation:            []string{},
	DeleteBranchNeonAuthTrustedDomainOperation:            []string{},
	DeleteBranchNeonAuthUserOperation:                     []string{},
	DeleteNeonAuthDomainFromRedirectURIWhitelistOperation: []string{},
	DeleteNeonAuthIntegrationOperation:                    []string{},
	DeleteNeonAuthOauthProviderOperation:                  []string{},
	DeleteNeonAuthUserOperation:                           []string{},
	DeleteOrganizationVPCEndpointOperation:                []string{},
	DeleteProjectOperation:                                []string{},
	DeleteProjectBranchOperation:                          []string{},
	DeleteProjectBranchDataAPIOperation:                   []string{},
	DeleteProjectBranchDatabaseOperation:                  []string{},
	DeleteProjectBranchRoleOperation:                      []string{},
	DeleteProjectEndpointOperation:                        []string{},
	DeleteProjectJWKSOperation:                            []string{},
	DeleteProjectVPCEndpointOperation:                     []string{},
	DeleteSnapshotOperation:                               []string{},
	DisableNeonAuthOperation:                              []string{},
	FinalizeRestoreBranchOperation:                        []string{},
	GetActiveRegionsOperation:                             []string{},
	GetAnonymizedBranchStatusOperation:                    []string{},
	GetAuthDetailsOperation:                               []string{},
	GetAvailablePreloadLibrariesOperation:                 []string{},
	GetConnectionURIOperation:                             []string{},
	GetConsumptionHistoryPerAccountOperation:              []string{},
	GetConsumptionHistoryPerProjectOperation:              []string{},
	GetConsumptionHistoryPerProjectV2Operation:            []string{},
	GetCurrentUserInfoOperation:                           []string{},
	GetCurrentUserOrganizationsOperation:                  []string{},
	GetMaskingRulesOperation:                              []string{},
	GetNeonAuthOperation:                                  []string{},
	GetNeonAuthAllowLocalhostOperation:                    []string{},
	GetNeonAuthEmailAndPasswordConfigOperation:            []string{},
	GetNeonAuthEmailProviderOperation:                     []string{},
	GetNeonAuthEmailServerOperation:                       []string{},
	GetNeonAuthPluginConfigsOperation:                     []string{},
	GetNeonAuthWebhookConfigOperation:                     []string{},
	GetOrganizationOperation:                              []string{},
	GetOrganizationInvitationsOperation:                   []string{},
	GetOrganizationMemberOperation:                        []string{},
	GetOrganizationMembersOperation:                       []string{},
	GetOrganizationVPCEndpointDetailsOperation:            []string{},
	GetProjectOperation:                                   []string{},
	GetProjectAdvisorSecurityIssuesOperation:              []string{},
	GetProjectBranchOperation:                             []string{},
	GetProjectBranchDataAPIOperation:                      []string{},
	GetProjectBranchDatabaseOperation:                     []string{},
	GetProjectBranchRoleOperation:                         []string{},
	GetProjectBranchRolePasswordOperation:                 []string{},
	GetProjectBranchSchemaOperation:                       []string{},
	GetProjectBranchSchemaComparisonOperation:             []string{},
	GetProjectEndpointOperation:                           []string{},
	GetProjectJWKSOperation:                               []string{},
	GetProjectOperationOperation:                          []string{},
	GetSnapshotScheduleOperation:                          []string{},
	GrantPermissionToProjectOperation:                     []string{},
	ListApiKeysOperation:                                  []string{},
	ListBranchNeonAuthOauthProvidersOperation:             []string{},
	ListBranchNeonAuthTrustedDomainsOperation:             []string{},
	ListNeonAuthIntegrationsOperation:                     []string{},
	ListNeonAuthOauthProvidersOperation:                   []string{},
	ListNeonAuthRedirectURIWhitelistDomainsOperation:      []string{},
	ListOrgApiKeysOperation:                               []string{},
	ListOrganizationVPCEndpointsOperation:                 []string{},
	ListOrganizationVPCEndpointsAllRegionsOperation:       []string{},
	ListProjectBranchDatabasesOperation:                   []string{},
	ListProjectBranchEndpointsOperation:                   []string{},
	ListProjectBranchRolesOperation:                       []string{},
	ListProjectBranchesOperation:                          []string{},
	ListProjectEndpointsOperation:                         []string{},
	ListProjectOperationsOperation:                        []string{},
	ListProjectPermissionsOperation:                       []string{},
	ListProjectVPCEndpointsOperation:                      []string{},
	ListProjectsOperation:                                 []string{},
	ListSharedProjectsOperation:                           []string{},
	ListSnapshotsOperation:                                []string{},
	RecoverProjectOperation:                               []string{},
	RemoveOrganizationMemberOperation:                     []string{},
	ResetProjectBranchRolePasswordOperation:               []string{},
	RestartProjectEndpointOperation:                       []string{},
	RestoreProjectOperation:                               []string{},
	RestoreProjectBranchOperation:                         []string{},
	RestoreSnapshotOperation:                              []string{},
	RevokeApiKeyOperation:                                 []string{},
	RevokeOrgApiKeyOperation:                              []string{},
	RevokePermissionFromProjectOperation:                  []string{},
	SendNeonAuthTestEmailOperation:                        []string{},
	SetDefaultProjectBranchOperation:                      []string{},
	SetSnapshotScheduleOperation:                          []string{},
	StartAnonymizationOperation:                           []string{},
	StartProjectEndpointOperation:                         []string{},
	SuspendProjectEndpointOperation:                       []string{},
	TransferNeonAuthProviderProjectOperation:              []string{},
	TransferProjectsFromOrgToOrgOperation:                 []string{},
	TransferProjectsFromUserToOrgOperation:                []string{},
	UpdateBranchNeonAuthOauthProviderOperation:            []string{},
	UpdateMaskingRulesOperation:                           []string{},
	UpdateNeonAuthAllowLocalhostOperation:                 []string{},
	UpdateNeonAuthEmailAndPasswordConfigOperation:         []string{},
	UpdateNeonAuthEmailProviderOperation:                  []string{},
	UpdateNeonAuthEmailServerOperation:                    []string{},
	UpdateNeonAuthOauthProviderOperation:                  []string{},
	UpdateNeonAuthOrganizationPluginOperation:             []string{},
	UpdateNeonAuthUserRoleOperation:                       []string{},
	UpdateNeonAuthWebhookConfigOperation:                  []string{},
	UpdateOrganizationMemberOperation:                     []string{},
	UpdateProjectOperation:                                []string{},
	UpdateProjectBranchOperation:                          []string{},
	UpdateProjectBranchDataAPIOperation:                   []string{},
	UpdateProjectBranchDatabaseOperation:                  []string{},
	UpdateProjectEndpointOperation:                        []string{},
	UpdateSnapshotOperation:                               []string{},
}

// GetRolesForCookieAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForCookieAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForCookieAuth(operation string) []string {
	roles, ok := operationRolesCookieAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesTokenCookieAuth is a private map storing roles per operation.
var operationRolesTokenCookieAuth = map[string][]string{
	AcceptProjectTransferRequestOperation:                 []string{},
	AddBranchNeonAuthOauthProviderOperation:               []string{},
	AddBranchNeonAuthTrustedDomainOperation:               []string{},
	AddNeonAuthDomainToRedirectURIWhitelistOperation:      []string{},
	AddNeonAuthOauthProviderOperation:                     []string{},
	AddProjectJWKSOperation:                               []string{},
	AssignOrganizationVPCEndpointOperation:                []string{},
	AssignProjectVPCEndpointOperation:                     []string{},
	CountProjectBranchesOperation:                         []string{},
	CreateApiKeyOperation:                                 []string{},
	CreateBranchNeonAuthNewUserOperation:                  []string{},
	CreateNeonAuthOperation:                               []string{},
	CreateNeonAuthIntegrationOperation:                    []string{},
	CreateNeonAuthNewUserOperation:                        []string{},
	CreateNeonAuthProviderSDKKeysOperation:                []string{},
	CreateOrgApiKeyOperation:                              []string{},
	CreateOrganizationInvitationsOperation:                []string{},
	CreateProjectOperation:                                []string{},
	CreateProjectBranchOperation:                          []string{},
	CreateProjectBranchAnonymizedOperation:                []string{},
	CreateProjectBranchDataAPIOperation:                   []string{},
	CreateProjectBranchDatabaseOperation:                  []string{},
	CreateProjectBranchRoleOperation:                      []string{},
	CreateProjectEndpointOperation:                        []string{},
	CreateProjectTransferRequestOperation:                 []string{},
	CreateSnapshotOperation:                               []string{},
	DeleteBranchNeonAuthOauthProviderOperation:            []string{},
	DeleteBranchNeonAuthTrustedDomainOperation:            []string{},
	DeleteBranchNeonAuthUserOperation:                     []string{},
	DeleteNeonAuthDomainFromRedirectURIWhitelistOperation: []string{},
	DeleteNeonAuthIntegrationOperation:                    []string{},
	DeleteNeonAuthOauthProviderOperation:                  []string{},
	DeleteNeonAuthUserOperation:                           []string{},
	DeleteOrganizationVPCEndpointOperation:                []string{},
	DeleteProjectOperation:                                []string{},
	DeleteProjectBranchOperation:                          []string{},
	DeleteProjectBranchDataAPIOperation:                   []string{},
	DeleteProjectBranchDatabaseOperation:                  []string{},
	DeleteProjectBranchRoleOperation:                      []string{},
	DeleteProjectEndpointOperation:                        []string{},
	DeleteProjectJWKSOperation:                            []string{},
	DeleteProjectVPCEndpointOperation:                     []string{},
	DeleteSnapshotOperation:                               []string{},
	DisableNeonAuthOperation:                              []string{},
	FinalizeRestoreBranchOperation:                        []string{},
	GetActiveRegionsOperation:                             []string{},
	GetAnonymizedBranchStatusOperation:                    []string{},
	GetAuthDetailsOperation:                               []string{},
	GetAvailablePreloadLibrariesOperation:                 []string{},
	GetConnectionURIOperation:                             []string{},
	GetConsumptionHistoryPerAccountOperation:              []string{},
	GetConsumptionHistoryPerProjectOperation:              []string{},
	GetConsumptionHistoryPerProjectV2Operation:            []string{},
	GetCurrentUserInfoOperation:                           []string{},
	GetCurrentUserOrganizationsOperation:                  []string{},
	GetMaskingRulesOperation:                              []string{},
	GetNeonAuthOperation:                                  []string{},
	GetNeonAuthAllowLocalhostOperation:                    []string{},
	GetNeonAuthEmailAndPasswordConfigOperation:            []string{},
	GetNeonAuthEmailProviderOperation:                     []string{},
	GetNeonAuthEmailServerOperation:                       []string{},
	GetNeonAuthPluginConfigsOperation:                     []string{},
	GetNeonAuthWebhookConfigOperation:                     []string{},
	GetOrganizationOperation:                              []string{},
	GetOrganizationInvitationsOperation:                   []string{},
	GetOrganizationMemberOperation:                        []string{},
	GetOrganizationMembersOperation:                       []string{},
	GetOrganizationVPCEndpointDetailsOperation:            []string{},
	GetProjectOperation:                                   []string{},
	GetProjectAdvisorSecurityIssuesOperation:              []string{},
	GetProjectBranchOperation:                             []string{},
	GetProjectBranchDataAPIOperation:                      []string{},
	GetProjectBranchDatabaseOperation:                     []string{},
	GetProjectBranchRoleOperation:                         []string{},
	GetProjectBranchRolePasswordOperation:                 []string{},
	GetProjectBranchSchemaOperation:                       []string{},
	GetProjectBranchSchemaComparisonOperation:             []string{},
	GetProjectEndpointOperation:                           []string{},
	GetProjectJWKSOperation:                               []string{},
	GetProjectOperationOperation:                          []string{},
	GetSnapshotScheduleOperation:                          []string{},
	GrantPermissionToProjectOperation:                     []string{},
	ListApiKeysOperation:                                  []string{},
	ListBranchNeonAuthOauthProvidersOperation:             []string{},
	ListBranchNeonAuthTrustedDomainsOperation:             []string{},
	ListNeonAuthIntegrationsOperation:                     []string{},
	ListNeonAuthOauthProvidersOperation:                   []string{},
	ListNeonAuthRedirectURIWhitelistDomainsOperation:      []string{},
	ListOrgApiKeysOperation:                               []string{},
	ListOrganizationVPCEndpointsOperation:                 []string{},
	ListOrganizationVPCEndpointsAllRegionsOperation:       []string{},
	ListProjectBranchDatabasesOperation:                   []string{},
	ListProjectBranchEndpointsOperation:                   []string{},
	ListProjectBranchRolesOperation:                       []string{},
	ListProjectBranchesOperation:                          []string{},
	ListProjectEndpointsOperation:                         []string{},
	ListProjectOperationsOperation:                        []string{},
	ListProjectPermissionsOperation:                       []string{},
	ListProjectVPCEndpointsOperation:                      []string{},
	ListProjectsOperation:                                 []string{},
	ListSharedProjectsOperation:                           []string{},
	ListSnapshotsOperation:                                []string{},
	RecoverProjectOperation:                               []string{},
	RemoveOrganizationMemberOperation:                     []string{},
	ResetProjectBranchRolePasswordOperation:               []string{},
	RestartProjectEndpointOperation:                       []string{},
	RestoreProjectOperation:                               []string{},
	RestoreProjectBranchOperation:                         []string{},
	RestoreSnapshotOperation:                              []string{},
	RevokeApiKeyOperation:                                 []string{},
	RevokeOrgApiKeyOperation:                              []string{},
	RevokePermissionFromProjectOperation:                  []string{},
	SendNeonAuthTestEmailOperation:                        []string{},
	SetDefaultProjectBranchOperation:                      []string{},
	SetSnapshotScheduleOperation:                          []string{},
	StartAnonymizationOperation:                           []string{},
	StartProjectEndpointOperation:                         []string{},
	SuspendProjectEndpointOperation:                       []string{},
	TransferNeonAuthProviderProjectOperation:              []string{},
	TransferProjectsFromOrgToOrgOperation:                 []string{},
	TransferProjectsFromUserToOrgOperation:                []string{},
	UpdateBranchNeonAuthOauthProviderOperation:            []string{},
	UpdateMaskingRulesOperation:                           []string{},
	UpdateNeonAuthAllowLocalhostOperation:                 []string{},
	UpdateNeonAuthEmailAndPasswordConfigOperation:         []string{},
	UpdateNeonAuthEmailProviderOperation:                  []string{},
	UpdateNeonAuthEmailServerOperation:                    []string{},
	UpdateNeonAuthOauthProviderOperation:                  []string{},
	UpdateNeonAuthOrganizationPluginOperation:             []string{},
	UpdateNeonAuthUserRoleOperation:                       []string{},
	UpdateNeonAuthWebhookConfigOperation:                  []string{},
	UpdateOrganizationMemberOperation:                     []string{},
	UpdateProjectOperation:                                []string{},
	UpdateProjectBranchOperation:                          []string{},
	UpdateProjectBranchDataAPIOperation:                   []string{},
	UpdateProjectBranchDatabaseOperation:                  []string{},
	UpdateProjectEndpointOperation:                        []string{},
	UpdateSnapshotOperation:                               []string{},
}

// GetRolesForTokenCookieAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForTokenCookieAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForTokenCookieAuth(operation string) []string {
	roles, ok := operationRolesTokenCookieAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BearerAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearerAuth[operationName]
	rctx, err := s.sec.HandleBearerAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityCookieAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t CookieAuth
	const parameterName = "zenith"
	var value string
	switch cookie, err := req.Cookie(parameterName); {
	case err == nil: // if NO error
		value = cookie.Value
	case errors.Is(err, http.ErrNoCookie):
		return ctx, false, nil
	default:
		return nil, false, errors.Wrap(err, "get cookie value")
	}
	t.APIKey = value
	t.Roles = operationRolesCookieAuth[operationName]
	rctx, err := s.sec.HandleCookieAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityTokenCookieAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t TokenCookieAuth
	const parameterName = "keycloak_token"
	var value string
	switch cookie, err := req.Cookie(parameterName); {
	case err == nil: // if NO error
		value = cookie.Value
	case errors.Is(err, http.ErrNoCookie):
		return ctx, false, nil
	default:
		return nil, false, errors.Wrap(err, "get cookie value")
	}
	t.APIKey = value
	t.Roles = operationRolesTokenCookieAuth[operationName]
	rctx, err := s.sec.HandleTokenCookieAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAuth provides BearerAuth security value.
	// The Neon API requires an API key to authorize your requests, which you can enter below.
	// Refer to our documentation to find out how to generate and use [API keys](https://neon.
	// tech/docs/manage/api-keys).
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
	// CookieAuth provides CookieAuth security value.
	CookieAuth(ctx context.Context, operationName OperationName) (CookieAuth, error)
	// TokenCookieAuth provides TokenCookieAuth security value.
	TokenCookieAuth(ctx context.Context, operationName OperationName) (TokenCookieAuth, error)
}

func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityCookieAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.CookieAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"CookieAuth\"")
	}
	req.AddCookie(&http.Cookie{
		Name:  "zenith",
		Value: t.APIKey,
	})
	return nil
}
func (s *Client) securityTokenCookieAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.TokenCookieAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"TokenCookieAuth\"")
	}
	req.AddCookie(&http.Cookie{
		Name:  "keycloak_token",
		Value: t.APIKey,
	})
	return nil
}
