// Code generated by ogen, DO NOT EDIT.

package neon

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AcceptProjectTransferRequest implements acceptProjectTransferRequest operation.
	//
	// Accepts a transfer request for the specified project, transferring it to the specified organization
	// or user. If org_id is not passed, the project will be transferred to the current user or
	// organization account.
	//
	// PUT /projects/{project_id}/transfer_requests/{request_id}
	AcceptProjectTransferRequest(ctx context.Context, req OptAcceptProjectTransferRequestReq, params AcceptProjectTransferRequestParams) (AcceptProjectTransferRequestRes, error)
	// AddBranchNeonAuthOauthProvider implements addBranchNeonAuthOauthProvider operation.
	//
	// Adds an OAuth provider configuration to the specified branch's Neon Auth integration.
	// After adding, users can authenticate using the configured provider.
	//
	// POST /projects/{project_id}/branches/{branch_id}/auth/oauth_providers
	AddBranchNeonAuthOauthProvider(ctx context.Context, req *NeonAuthAddOAuthProviderRequest, params AddBranchNeonAuthOauthProviderParams) (*NeonAuthOauthProvider, error)
	// AddBranchNeonAuthTrustedDomain implements addBranchNeonAuthTrustedDomain operation.
	//
	// Adds a domain to the redirect URI whitelist for the specified branch.
	// Only domains in this list are permitted as redirect targets after authentication.
	//
	// POST /projects/{project_id}/branches/{branch_id}/auth/domains
	AddBranchNeonAuthTrustedDomain(ctx context.Context, req *NeonAuthAddDomainToRedirectURIWhitelistRequest, params AddBranchNeonAuthTrustedDomainParams) error
	// AddNeonAuthDomainToRedirectURIWhitelist implements addNeonAuthDomainToRedirectURIWhitelist operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/domains` instead. Adds a domain
	// to the redirect_uri whitelist for the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /projects/{project_id}/auth/domains
	AddNeonAuthDomainToRedirectURIWhitelist(ctx context.Context, req *NeonAuthAddDomainToRedirectURIWhitelistRequest, params AddNeonAuthDomainToRedirectURIWhitelistParams) error
	// AddNeonAuthOauthProvider implements addNeonAuthOauthProvider operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/oauth_providers` instead.
	// Adds an OAuth provider to the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /projects/{project_id}/auth/oauth_providers
	AddNeonAuthOauthProvider(ctx context.Context, req *NeonAuthAddOAuthProviderRequest, params AddNeonAuthOauthProviderParams) (*NeonAuthOauthProvider, error)
	// AddProjectJWKS implements addProjectJWKS operation.
	//
	// Adds a JWKS URL to the specified project for verifying JWTs used as the authentication mechanism.
	// The URL must be a valid HTTPS URL that returns a JSON Web Key Set.
	// The `provider_name` field allows you to specify which authentication provider you're using (e.g.,
	// Clerk, Auth0, AWS Cognito).
	// The `branch_id` scopes the JWKS URL to specific branches; if not specified, it applies to all
	// branches.
	// The `role_names` scopes the URL to specific roles; if not specified, default roles are used
	// (`authenticator`, `authenticated`, `anonymous`).
	// The `jwt_audience` specifies which `aud` values are accepted in JWTs.
	//
	// POST /projects/{project_id}/jwks
	AddProjectJWKS(ctx context.Context, req *AddProjectJWKSRequest, params AddProjectJWKSParams) (*JWKSCreationOperation, error)
	// AssignOrganizationVPCEndpoint implements assignOrganizationVPCEndpoint operation.
	//
	// Assigns a VPC endpoint to a Neon organization or updates its existing assignment.
	//
	// POST /organizations/{org_id}/vpc/region/{region_id}/vpc_endpoints/{vpc_endpoint_id}
	AssignOrganizationVPCEndpoint(ctx context.Context, req *VPCEndpointAssignment, params AssignOrganizationVPCEndpointParams) error
	// AssignProjectVPCEndpoint implements assignProjectVPCEndpoint operation.
	//
	// Sets or updates a VPC endpoint restriction for a Neon project.
	// When a VPC endpoint restriction is set, the project only accepts connections
	// from the specified VPC.
	// A VPC endpoint can be set as a restriction only after it is assigned to the
	// parent organization of the Neon project.
	//
	// POST /projects/{project_id}/vpc_endpoints/{vpc_endpoint_id}
	AssignProjectVPCEndpoint(ctx context.Context, req *VPCEndpointAssignment, params AssignProjectVPCEndpointParams) error
	// CountProjectBranches implements countProjectBranches operation.
	//
	// Retrieves the total number of branches in the specified project.
	// Supports an optional `search` parameter to count branches matching a name filter.
	//
	// GET /projects/{project_id}/branches/count
	CountProjectBranches(ctx context.Context, params CountProjectBranchesParams) (*BranchesCountResponse, error)
	// CreateApiKey implements createApiKey operation.
	//
	// Creates an API key.
	// The `key_name` is a user-specified name for the key.
	// Returns an `id` and `key`; the `key` is a randomly generated, 64-bit token required to access the
	// Neon API.
	// Store the key securely — it is only returned once.
	// API keys can also be managed in the Neon Console.
	// See [Manage API keys](https://neon.com/docs/manage/api-keys/).
	//
	// POST /api_keys
	CreateApiKey(ctx context.Context, req *ApiKeyCreateRequest) (*ApiKeyCreateResponse, error)
	// CreateBranchNeonAuthNewUser implements createBranchNeonAuthNewUser operation.
	//
	// Creates a new user in the Neon Auth user directory for the specified branch.
	// The user is created in the `neon_auth.users_sync` table and can immediately authenticate
	// using the branch's configured auth providers.
	//
	// POST /projects/{project_id}/branches/{branch_id}/auth/users
	CreateBranchNeonAuthNewUser(ctx context.Context, req *CreateBranchNeonAuthNewUserRequest, params CreateBranchNeonAuthNewUserParams) (*NeonAuthCreateNewUserResponse, error)
	// CreateCredential implements createCredential operation.
	//
	// Issues a new scoped service credential anchored to the specified
	// branch. The response carries `api_token` and `s3_secret_access_key`
	// exactly once — they are not stored server-side.
	// **Note**: This endpoint is currently in Private Beta.
	//
	// POST /projects/{project_id}/branches/{branch_id}/credentials
	CreateCredential(ctx context.Context, req *CreateCredentialRequest, params CreateCredentialParams) (*CreateCredentialResponse, error)
	// CreateNeonAuth implements createNeonAuth operation.
	//
	// Enables Neon Auth for the specified branch by connecting it to an authentication provider.
	// Creating the integration provisions the `neon_auth` schema in the branch database, which stores
	// user identity data synchronized from the provider.
	//
	// POST /projects/{project_id}/branches/{branch_id}/auth
	CreateNeonAuth(ctx context.Context, req *EnableNeonAuthIntegrationRequest, params CreateNeonAuthParams) (*NeonAuthCreateIntegrationResponse, error)
	// CreateNeonAuthIntegration implements createNeonAuthIntegration operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth` instead. Creates a project on a
	// third-party authentication provider's platform for use with Neon Auth.
	// Use this endpoint if the frontend integration flow can't be used.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /projects/auth/create
	CreateNeonAuthIntegration(ctx context.Context, req *NeonAuthCreateIntegrationRequest) (*NeonAuthCreateIntegrationResponse, error)
	// CreateNeonAuthNewUser implements createNeonAuthNewUser operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/users` instead. Creates a new
	// user in Neon Auth.
	// The user will be created in your neon_auth.users_sync table and automatically propagated to your
	// auth project, whether Neon-managed or provider-owned.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /projects/auth/user
	CreateNeonAuthNewUser(ctx context.Context, req *NeonAuthCreateNewUserRequest) (*NeonAuthCreateNewUserResponse, error)
	// CreateNeonAuthProviderSDKKeys implements createNeonAuthProviderSDKKeys operation.
	//
	// Generates SDK or API Keys for the auth provider. These might be called different things depending
	// on the auth provider you're using, but are generally used for setting up the frontend and backend
	// SDKs.
	//
	// POST /projects/auth/keys
	CreateNeonAuthProviderSDKKeys(ctx context.Context, req *NeonAuthCreateAuthProviderSDKKeysRequest) (*NeonAuthCreateIntegrationResponse, error)
	// CreateOrgApiKey implements createOrgApiKey operation.
	//
	// Creates an API key for the specified organization.
	// The `key_name` is a user-specified name for the key.
	// Returns an `id` and `key`; the `key` is a randomly generated, 64-bit token required to access the
	// Neon API.
	// Store the key securely — it is only returned once.
	// API keys can also be managed in the Neon Console.
	// See [Manage API keys](https://neon.com/docs/manage/api-keys/).
	//
	// POST /organizations/{org_id}/api_keys
	CreateOrgApiKey(ctx context.Context, req *OrgApiKeyCreateRequest, params CreateOrgApiKeyParams) (*OrgApiKeyCreateResponse, error)
	// CreateOrganizationInvitations implements createOrganizationInvitations operation.
	//
	// Creates invitations for a specific organization.
	// If the invited user has an existing account, they automatically join as a member.
	// If they don't yet have an account, they are invited to create one, after which they become a
	// member.
	// Each invited user receives an email notification.
	//
	// POST /organizations/{org_id}/invitations
	CreateOrganizationInvitations(ctx context.Context, req *OrganizationInvitesCreateRequest, params CreateOrganizationInvitationsParams) (*OrganizationInvitationsResponse, error)
	// CreateProject implements createProject operation.
	//
	// Creates a Neon project within an organization.
	// If using a personal API key, include the `org_id` parameter to specify which organization to
	// create the project in.
	// If using an org API key, `org_id` is automatically inferred from the key.
	// Plan limits define how many projects you can create.
	// For more information, see [Manage projects](https://neon.com/docs/manage/projects/).
	// You can specify a region and Postgres version in the request body.
	// Neon currently supports PostgreSQL 14, 15, 16, 17, and 18.
	// For supported regions and `region_id` values, see [Regions](https://neon.
	// com/docs/introduction/regions/).
	//
	// POST /projects
	CreateProject(ctx context.Context, req *ProjectCreateRequest) (*CreatedProject, error)
	// CreateProjectBranch implements createProjectBranch operation.
	//
	// Creates a branch in the specified project.
	// No request body is required, but you can specify one to create a compute endpoint or select a
	// non-default parent branch.
	// By default, the branch is created from the project's default branch with no compute endpoint, and
	// the branch name is auto-generated.
	// To access the branch, add a `read_write` endpoint.
	// Each branch supports one read-write endpoint and multiple read-only endpoints.
	// For related information, see [Manage branches](https://neon.com/docs/manage/branches/).
	//
	// POST /projects/{project_id}/branches
	CreateProjectBranch(ctx context.Context, req OptCreateProjectBranchReq, params CreateProjectBranchParams) (*CreatedBranch, error)
	// CreateProjectBranchAnonymized implements createProjectBranchAnonymized operation.
	//
	// Creates a new branch with anonymized data using PostgreSQL Anonymizer for static masking.
	// This allows developers to work with masked production data.
	// Optionally, provide `masking_rules` to set initial masking rules for the branch
	// and `start_anonymization` to automatically start anonymization after creation. This
	// combines functionality of updating masking rules and starting anonymization into the
	// branch creation request.
	// **Note**: This endpoint is currently in Beta.
	//
	// POST /projects/{project_id}/branch_anonymized
	CreateProjectBranchAnonymized(ctx context.Context, req *BranchAnonymizedCreateRequest, params CreateProjectBranchAnonymizedParams) (*CreatedBranch, error)
	// CreateProjectBranchBucket implements createProjectBranchBucket operation.
	//
	// Creates a new branchable object-storage bucket on the specified branch.
	// Buckets are managed by the Neon Platform branchable-storage service.
	// **Note**: This endpoint is currently in Private Beta.
	//
	// POST /projects/{project_id}/branches/{branch_id}/buckets
	CreateProjectBranchBucket(ctx context.Context, req *BucketCreateRequest, params CreateProjectBranchBucketParams) (CreateProjectBranchBucketRes, error)
	// CreateProjectBranchDataAPI implements createProjectBranchDataAPI operation.
	//
	// Creates a new instance of Neon Data API in the specified branch.
	// The Data API exposes a REST interface over the branch database. The `database_name` path parameter
	// determines which database the API serves.
	//
	// POST /projects/{project_id}/branches/{branch_id}/data-api/{database_name}
	CreateProjectBranchDataAPI(ctx context.Context, req OptDataAPICreateRequest, params CreateProjectBranchDataAPIParams) (*DataAPICreateResponse, error)
	// CreateProjectBranchDatabase implements createProjectBranchDatabase operation.
	//
	// Creates a database in the specified branch.
	// A branch can have multiple databases.
	// For related information, see [Manage databases](https://neon.com/docs/manage/databases/).
	//
	// POST /projects/{project_id}/branches/{branch_id}/databases
	CreateProjectBranchDatabase(ctx context.Context, req *DatabaseCreateRequest, params CreateProjectBranchDatabaseParams) (*DatabaseOperations, error)
	// CreateProjectBranchFunctionDeployment implements createProjectBranchFunctionDeployment operation.
	//
	// Creates a deployment for the function. Supply any subset of zip,
	// environment, and runtime; omitted fields inherit the
	// function's latest version. At least one field must be supplied. The
	// first deployment of a function must include zip. The newest deployment
	// becomes active.
	// **Note**: This endpoint is currently in Private Beta.
	//
	// POST /projects/{project_id}/branches/{branch_id}/functions/{slug}/deployments
	CreateProjectBranchFunctionDeployment(ctx context.Context, req *FunctionDeployRequestMultipart, params CreateProjectBranchFunctionDeploymentParams) (*NeonFunctionDeploymentResponse, error)
	// CreateProjectBranchRole implements createProjectBranchRole operation.
	//
	// Creates a Postgres role in the specified branch.
	// For related information, see [Manage roles](https://neon.com/docs/manage/roles/).
	// Connections established to the active compute endpoint will be dropped.
	// If the compute endpoint is idle, the endpoint becomes active for a short period of time and is
	// suspended afterward.
	//
	// POST /projects/{project_id}/branches/{branch_id}/roles
	CreateProjectBranchRole(ctx context.Context, req *RoleCreateRequest, params CreateProjectBranchRoleParams) (*RoleOperations, error)
	// CreateProjectEndpoint implements createProjectEndpoint operation.
	//
	// Creates a compute endpoint for the specified branch.
	// A compute endpoint is a Neon compute instance.
	// There is a maximum of one read-write compute endpoint per branch.
	// If the specified branch already has a read-write compute endpoint, the operation fails.
	// A branch can have multiple read-only compute endpoints.
	// For more information about compute endpoints, see [Manage computes](https://neon.
	// com/docs/manage/endpoints/).
	//
	// POST /projects/{project_id}/endpoints
	CreateProjectEndpoint(ctx context.Context, req *EndpointCreateRequest, params CreateProjectEndpointParams) (*EndpointOperations, error)
	// CreateProjectTransferRequest implements createProjectTransferRequest operation.
	//
	// Creates a transfer request for the specified project. The request expires after a set period.
	// To accept the request, the recipient calls `PUT
	// /projects/{project_id}/transfer_requests/{request_id}`
	// or uses the Neon Console claim link.
	// The optional `ru` parameter redirects the recipient after acceptance.
	//
	// POST /projects/{project_id}/transfer_requests
	CreateProjectTransferRequest(ctx context.Context, req OptCreateProjectTransferRequestReq, params CreateProjectTransferRequestParams) (*ProjectTransferRequestResponse, error)
	// CreateSnapshot implements createSnapshot operation.
	//
	// Creates a snapshot from the specified branch.
	// This operation may initiate an asynchronous process.
	// **Note**: This endpoint is currently in Beta.
	//
	// POST /projects/{project_id}/branches/{branch_id}/snapshot
	CreateSnapshot(ctx context.Context, params CreateSnapshotParams) (*CreateSnapshotOK, error)
	// DeleteBranchNeonAuthOauthProvider implements deleteBranchNeonAuthOauthProvider operation.
	//
	// Deletes a OAuth provider from the specified project.
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/auth/oauth_providers/{oauth_provider_id}
	DeleteBranchNeonAuthOauthProvider(ctx context.Context, params DeleteBranchNeonAuthOauthProviderParams) error
	// DeleteBranchNeonAuthTrustedDomain implements deleteBranchNeonAuthTrustedDomain operation.
	//
	// Removes a domain from the redirect URI whitelist for the specified branch.
	// After removal, the domain can no longer be used as a redirect target after authentication.
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/auth/domains
	DeleteBranchNeonAuthTrustedDomain(ctx context.Context, req *NeonAuthDeleteDomainFromRedirectURIWhitelistRequest, params DeleteBranchNeonAuthTrustedDomainParams) error
	// DeleteBranchNeonAuthUser implements deleteBranchNeonAuthUser operation.
	//
	// Deletes the specified user from the Neon Auth user directory for the specified branch.
	// Removes the user record from `neon_auth.users_sync`. This action cannot be undone.
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/auth/users/{auth_user_id}
	DeleteBranchNeonAuthUser(ctx context.Context, params DeleteBranchNeonAuthUserParams) error
	// DeleteNeonAuthDomainFromRedirectURIWhitelist implements deleteNeonAuthDomainFromRedirectURIWhitelist operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/domains` instead. Deletes a
	// domain from the redirect_uri whitelist for the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// DELETE /projects/{project_id}/auth/domains
	DeleteNeonAuthDomainFromRedirectURIWhitelist(ctx context.Context, req *NeonAuthDeleteDomainFromRedirectURIWhitelistRequest, params DeleteNeonAuthDomainFromRedirectURIWhitelistParams) error
	// DeleteNeonAuthIntegration implements deleteNeonAuthIntegration operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth` instead.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// DELETE /projects/{project_id}/auth/integration/{auth_provider}
	DeleteNeonAuthIntegration(ctx context.Context, req OptDeleteNeonAuthIntegrationReq, params DeleteNeonAuthIntegrationParams) error
	// DeleteNeonAuthOauthProvider implements deleteNeonAuthOauthProvider operation.
	//
	// DEPRECATED, use
	// `/projects/{project_id}/branches/{branch_id}/auth/oauth_providers/{oauth_provider_id}` instead.
	// Deletes a OAuth provider from the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// DELETE /projects/{project_id}/auth/oauth_providers/{oauth_provider_id}
	DeleteNeonAuthOauthProvider(ctx context.Context, params DeleteNeonAuthOauthProviderParams) error
	// DeleteNeonAuthUser implements deleteNeonAuthUser operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/users/{auth_user_id}` instead.
	// Deletes the auth user for the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// DELETE /projects/{project_id}/auth/users/{auth_user_id}
	DeleteNeonAuthUser(ctx context.Context, params DeleteNeonAuthUserParams) error
	// DeleteOrganizationSpendingLimit implements deleteOrganizationSpendingLimit operation.
	//
	// Removes the configured monthly spending limit for the specified organization.
	// Idempotent — removing an already-unset limit still succeeds.
	// Available to organization admins on Launch and Scale plans only.
	//
	// DELETE /organizations/{org_id}/billing/spending_limit
	DeleteOrganizationSpendingLimit(ctx context.Context, params DeleteOrganizationSpendingLimitParams) error
	// DeleteOrganizationVPCEndpoint implements deleteOrganizationVPCEndpoint operation.
	//
	// Deletes the VPC endpoint from the specified Neon organization.
	// If you delete a VPC endpoint from a Neon organization, that VPC endpoint cannot
	// be added back to the Neon organization.
	//
	// DELETE /organizations/{org_id}/vpc/region/{region_id}/vpc_endpoints/{vpc_endpoint_id}
	DeleteOrganizationVPCEndpoint(ctx context.Context, params DeleteOrganizationVPCEndpointParams) error
	// DeleteProject implements deleteProject operation.
	//
	// Deletes the specified project and all its endpoints, branches, databases, and users.
	// Deleted projects can be recovered within 7 days using `POST /projects/{project_id}/recover`.
	// To list recoverable projects, use `GET /projects?recoverable=true`.
	//
	// DELETE /projects/{project_id}
	DeleteProject(ctx context.Context, params DeleteProjectParams) (*ProjectResponse, error)
	// DeleteProjectBranch implements deleteProjectBranch operation.
	//
	// Deletes the specified branch from a project and places all compute endpoints into an idle state,
	// breaking existing client connections.
	// The deletion completes after all operations finish.
	// You cannot delete a project's root or default branch, or a branch that has a child branch.
	// A project must have at least one branch.
	// By default, deleted branches can be recovered within a 7-day grace period.
	// Use the `hard_delete` parameter to permanently delete the branch immediately.
	// For related information, see [Manage branches](https://neon.com/docs/manage/branches/).
	//
	// DELETE /projects/{project_id}/branches/{branch_id}
	DeleteProjectBranch(ctx context.Context, params DeleteProjectBranchParams) (DeleteProjectBranchRes, error)
	// DeleteProjectBranchBucket implements deleteProjectBranchBucket operation.
	//
	// Deletes the named bucket from the specified branch.
	// **Note**: This endpoint is currently in Private Beta.
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/buckets/{bucket_name}
	DeleteProjectBranchBucket(ctx context.Context, params DeleteProjectBranchBucketParams) (DeleteProjectBranchBucketRes, error)
	// DeleteProjectBranchBucketObject implements deleteProjectBranchBucketObject operation.
	//
	// Deletes the named object from the bucket on the specified branch.
	// Served by the user's session (no customer S3 credentials required).
	// **Note**: This endpoint is currently in Private Beta.
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/buckets/{bucket_name}/objects/{object_key}
	DeleteProjectBranchBucketObject(ctx context.Context, params DeleteProjectBranchBucketObjectParams) (DeleteProjectBranchBucketObjectRes, error)
	// DeleteProjectBranchBucketObjectsByPrefix implements deleteProjectBranchBucketObjectsByPrefix operation.
	//
	// Soft-deletes every object on the specified branch whose key starts with
	// `prefix`, in a single call. Intended to back a "delete folder" action in
	// an object browser: a `prefix` of `app/avatars/` removes every object
	// beneath that folder. Served by the user's session (no customer S3
	// credentials required).
	// `prefix` must be non-empty, end with `/`, be at most 1024 bytes, and
	// contain no control characters - a partial-segment prefix cannot
	// accidentally delete sibling keys. Returns the number of objects
	// soft-deleted (`deleted`), which may be 0 when no live object matched the
	// prefix on this branch.
	// Only objects physically present on this branch are tombstoned; objects
	// inherited from an ancestor branch via copy-on-write (not materialized on
	// this branch) are out of scope.
	// **Note**: This endpoint is currently in Private Beta.
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/buckets/{bucket_name}/objects-by-prefix
	DeleteProjectBranchBucketObjectsByPrefix(ctx context.Context, params DeleteProjectBranchBucketObjectsByPrefixParams) (DeleteProjectBranchBucketObjectsByPrefixRes, error)
	// DeleteProjectBranchDataAPI implements deleteProjectBranchDataAPI operation.
	//
	// Deletes the Neon Data API for the specified branch.
	// Existing connections using the Data API endpoint will fail after deletion.
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/data-api/{database_name}
	DeleteProjectBranchDataAPI(ctx context.Context, params DeleteProjectBranchDataAPIParams) error
	// DeleteProjectBranchDatabase implements deleteProjectBranchDatabase operation.
	//
	// Deletes the specified database from the branch.
	// For related information, see [Manage databases](https://neon.com/docs/manage/databases/).
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/databases/{database_name}
	DeleteProjectBranchDatabase(ctx context.Context, params DeleteProjectBranchDatabaseParams) (DeleteProjectBranchDatabaseRes, error)
	// DeleteProjectBranchFunction implements deleteProjectBranchFunction operation.
	//
	// Deletes the function identified by its slug.
	// **Note**: This endpoint is currently in Private Beta.
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/functions/{slug}
	DeleteProjectBranchFunction(ctx context.Context, params DeleteProjectBranchFunctionParams) error
	// DeleteProjectBranchRole implements deleteProjectBranchRole operation.
	//
	// Deletes the specified Postgres role from the branch.
	// For related information, see [Manage roles](https://neon.com/docs/manage/roles/).
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/roles/{role_name}
	DeleteProjectBranchRole(ctx context.Context, params DeleteProjectBranchRoleParams) (DeleteProjectBranchRoleRes, error)
	// DeleteProjectEndpoint implements deleteProjectEndpoint operation.
	//
	// Deletes the specified compute endpoint.
	// A compute endpoint is a Neon compute instance.
	// Deleting a compute endpoint drops existing network connections to the compute endpoint.
	// The deletion is completed when the last operation in the chain finishes successfully.
	// An `endpoint_id` has an `ep-` prefix.
	// For information about compute endpoints, see [Manage computes](https://neon.
	// com/docs/manage/endpoints/).
	//
	// DELETE /projects/{project_id}/endpoints/{endpoint_id}
	DeleteProjectEndpoint(ctx context.Context, params DeleteProjectEndpointParams) (DeleteProjectEndpointRes, error)
	// DeleteProjectJWKS implements deleteProjectJWKS operation.
	//
	// Removes the specified JWKS URL from the project.
	// JWTs signed by keys from the removed URL can no longer authenticate to the project's endpoints.
	//
	// DELETE /projects/{project_id}/jwks/{jwks_id}
	DeleteProjectJWKS(ctx context.Context, params DeleteProjectJWKSParams) (*JWKS, error)
	// DeleteProjectVPCEndpoint implements deleteProjectVPCEndpoint operation.
	//
	// Removes the specified VPC endpoint restriction from a Neon project.
	//
	// DELETE /projects/{project_id}/vpc_endpoints/{vpc_endpoint_id}
	DeleteProjectVPCEndpoint(ctx context.Context, params DeleteProjectVPCEndpointParams) error
	// DeleteSnapshot implements deleteSnapshot operation.
	//
	// Deletes the specified snapshot.
	// **Note**: This endpoint is currently in Beta.
	//
	// DELETE /projects/{project_id}/snapshots/{snapshot_id}
	DeleteSnapshot(ctx context.Context, params DeleteSnapshotParams) (*OperationsResponse, error)
	// DisableNeonAuth implements disableNeonAuth operation.
	//
	// Disables the Neon Auth integration for the specified branch, removing the connection
	// to the authentication provider.
	// If `delete_data` is `true`, also deletes the `neon_auth` schema and all associated tables
	// from the branch database.
	// The integration can be re-enabled by calling `POST
	// /projects/{project_id}/branches/{branch_id}/auth`.
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/auth
	DisableNeonAuth(ctx context.Context, req OptDisableNeonAuthReq, params DisableNeonAuthParams) error
	// FinalizeRestoreBranch implements finalizeRestoreBranch operation.
	//
	// Finalize the restore operation for a branch created from a snapshot.
	// This operation updates the branch so it functions as the original branch it replaced.
	// This includes:
	// - Reassigning any computes from the original branch to the restored branch (this will restart the
	// computes)
	// - Renaming the restored branch to the original branch's name
	// - Renaming the original branch so it no longer uses the original name
	// This operation only applies to branches created using the `restoreSnapshot` endpoint with
	// `finalize_restore: false`.
	// **Note**: This endpoint is currently in Beta.
	//
	// POST /projects/{project_id}/branches/{branch_id}/finalize_restore
	FinalizeRestoreBranch(ctx context.Context, req OptFinalizeRestoreBranchReq, params FinalizeRestoreBranchParams) (*OperationsResponse, error)
	// GetActiveRegions implements getActiveRegions operation.
	//
	// Lists supported Neon regions.
	// **Note:** Not all regions are available to all organizations. Pass the `org_id`
	// parameter to get an accurate list of regions available to your organization.
	//
	// GET /regions
	GetActiveRegions(ctx context.Context, params GetActiveRegionsParams) (*ActiveRegionsResponse, error)
	// GetAnonymizedBranchStatus implements getAnonymizedBranchStatus operation.
	//
	// Retrieves the current status of an anonymized branch, including its state and progress information.
	// This endpoint allows you to monitor the anonymization process from initialization through
	// completion.
	// Only anonymized branches will have status information available.
	// **Note**: This endpoint is currently in Beta.
	//
	// GET /projects/{project_id}/branches/{branch_id}/anonymized_status
	GetAnonymizedBranchStatus(ctx context.Context, params GetAnonymizedBranchStatusParams) (*AnonymizedBranchStatusResponse, error)
	// GetAuthDetails implements getAuthDetails operation.
	//
	// Returns authentication details for the credentials used in the request,
	// including the credential type (API key, Bearer token, or OAuth session)
	// and the associated identity.
	//
	// GET /auth
	GetAuthDetails(ctx context.Context) (*AuthDetailsResponse, error)
	// GetAvailablePreloadLibraries implements getAvailablePreloadLibraries operation.
	//
	// Returns the shared preload libraries available for the specified project's Postgres version.
	// Shared preload libraries are Postgres extensions that require the `shared_preload_libraries`
	// setting and a compute restart to activate.
	// Use this list to determine which libraries can be enabled in the project's
	// `settings.preload_libraries` configuration.
	//
	// GET /projects/{project_id}/available_preload_libraries
	GetAvailablePreloadLibraries(ctx context.Context, params GetAvailablePreloadLibrariesParams) (*AvailablePreloadLibraries, error)
	// GetConnectionURI implements getConnectionURI operation.
	//
	// Retrieves a connection URI for the specified database.
	// The URI uses the standard PostgreSQL connection string format. Set `pooled=true` to include the
	// `-pooler` suffix for a connection pooler URI.
	//
	// GET /projects/{project_id}/connection_uri
	GetConnectionURI(ctx context.Context, params GetConnectionURIParams) (*ConnectionURIResponse, error)
	// GetConsumptionHistoryPerBranchV2 implements getConsumptionHistoryPerBranchV2 operation.
	//
	// Returns consumption metrics for each branch across one or more projects listed in
	// `project_ids` (1 to 100 projects). Available for accounts on paid usage-based Launch, Scale,
	// Agent, and Enterprise plans.
	// History starts when the account first ingests branch-level consumption data.
	// The `metrics` query parameter is required. Only these six values are supported on this
	// endpoint:
	// `compute_unit_seconds`, `root_branch_bytes_month`, `child_branch_bytes_month`,
	// `instant_restore_bytes_month`, `public_network_transfer_bytes`, `private_network_transfer_bytes`.
	// This endpoint does not support `extra_branches_month` or `snapshot_storage_bytes_month`.
	// Use `GET /consumption_history/v2/projects` for those.
	// Consumption metrics within each branch are returned in ascending time order (oldest first).
	// This request does not wake project computes.
	//
	// GET /consumption_history/v2/branches
	GetConsumptionHistoryPerBranchV2(ctx context.Context, params GetConsumptionHistoryPerBranchV2Params) (GetConsumptionHistoryPerBranchV2Res, error)
	// GetConsumptionHistoryPerProject implements getConsumptionHistoryPerProject operation.
	//
	// Retrieves consumption metrics for Scale, Business, and Enterprise plan projects. History begins at
	// the time of upgrade.
	// Results are ordered by time in ascending order (oldest to newest).
	// Issuing a call to this API does not wake a project's compute endpoint.
	//
	// GET /consumption_history/projects
	GetConsumptionHistoryPerProject(ctx context.Context, params GetConsumptionHistoryPerProjectParams) (GetConsumptionHistoryPerProjectRes, error)
	// GetConsumptionHistoryPerProjectV2 implements getConsumptionHistoryPerProjectV2 operation.
	//
	// Returns consumption metrics for up to `limit` projects per page. If `project_ids` is omitted,
	// projects in the organization are included across pages (use `cursor`). If `project_ids` is
	// provided, the response is limited to those projects (up to 100). Available for accounts on
	// Launch, Scale, Agent, Business, and Enterprise plans.
	// History starts when the account upgrades to an eligible plan.
	// The `metrics` query parameter is required. Supported values:
	// `compute_unit_seconds`, `root_branch_bytes_month`, `child_branch_bytes_month`,
	// `instant_restore_bytes_month`, `public_network_transfer_bytes`, `private_network_transfer_bytes`,
	// `extra_branches_month`, `snapshot_storage_bytes_month`.
	// Consumption metrics within each project are returned in ascending time order (oldest first).
	// This request does not wake project computes.
	//
	// GET /consumption_history/v2/projects
	GetConsumptionHistoryPerProjectV2(ctx context.Context, params GetConsumptionHistoryPerProjectV2Params) (GetConsumptionHistoryPerProjectV2Res, error)
	// GetCurrentUserInfo implements getCurrentUserInfo operation.
	//
	// Retrieves information about the currently authenticated Neon user,
	// including account identifiers, plan details, and linked auth accounts.
	//
	// GET /users/me
	GetCurrentUserInfo(ctx context.Context) (*CurrentUserInfoResponse, error)
	// GetCurrentUserOrganizations implements getCurrentUserOrganizations operation.
	//
	// Retrieves the organizations that the currently authenticated user belongs to.
	// When called with an organization- or project-scoped API key (which is not
	// tied to a user), this returns the single organization that owns the key.
	//
	// GET /users/me/organizations
	GetCurrentUserOrganizations(ctx context.Context) (*OrganizationsResponse, error)
	// GetMaskingRules implements getMaskingRules operation.
	//
	// Retrieves the masking rules for the specified anonymized branch.
	// Masking rules define how sensitive data should be anonymized using PostgreSQL Anonymizer.
	// **Note**: This endpoint is currently in Beta.
	//
	// GET /projects/{project_id}/branches/{branch_id}/masking_rules
	GetMaskingRules(ctx context.Context, params GetMaskingRulesParams) (*MaskingRulesResponse, error)
	// GetNeonAuth implements getNeonAuth operation.
	//
	// Retrieves the Neon Auth integration details for the specified branch,
	// including the auth provider type and integration status.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth
	GetNeonAuth(ctx context.Context, params GetNeonAuthParams) (*NeonAuthIntegration, error)
	// GetNeonAuthAllowLocalhost implements getNeonAuthAllowLocalhost operation.
	//
	// Retrieves the localhost allow setting for the specified branch's Neon Auth integration.
	// When enabled, authentication flows work from `localhost` without adding it to the redirect URI
	// whitelist.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth/allow_localhost
	GetNeonAuthAllowLocalhost(ctx context.Context, params GetNeonAuthAllowLocalhostParams) (*NeonAuthAllowLocalhostResponse, error)
	// GetNeonAuthEmailAndPasswordConfig implements getNeonAuthEmailAndPasswordConfig operation.
	//
	// Retrieves the email and password authentication configuration for the specified branch's Neon Auth
	// integration,
	// including whether it is enabled and the email verification method.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth/email_and_password
	GetNeonAuthEmailAndPasswordConfig(ctx context.Context, params GetNeonAuthEmailAndPasswordConfigParams) (*NeonAuthEmailAndPasswordConfig, error)
	// GetNeonAuthEmailProvider implements getNeonAuthEmailProvider operation.
	//
	// Retrieves the email provider configuration for the specified branch's Neon Auth integration,
	// including the provider type and server settings.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth/email_provider
	GetNeonAuthEmailProvider(ctx context.Context, params GetNeonAuthEmailProviderParams) (*NeonAuthEmailServerConfig, error)
	// GetNeonAuthEmailServer implements getNeonAuthEmailServer operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/email_provider` instead. Gets
	// the email server configuration for the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /projects/{project_id}/auth/email_server
	GetNeonAuthEmailServer(ctx context.Context, params GetNeonAuthEmailServerParams) (*NeonAuthEmailServerConfig, error)
	// GetNeonAuthPhoneNumberPlugin implements getNeonAuthPhoneNumberPlugin operation.
	//
	// Returns the phone number plugin configuration for Neon Auth.
	// The phone number plugin enables phone-based OTP authentication.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth/plugins/phone-number
	GetNeonAuthPhoneNumberPlugin(ctx context.Context, params GetNeonAuthPhoneNumberPluginParams) (*NeonAuthPhoneNumberConfig, error)
	// GetNeonAuthPluginConfigs implements getNeonAuthPluginConfigs operation.
	//
	// Returns all plugin configurations for Neon Auth in a single response.
	// This endpoint aggregates organization, email provider, email and password,
	// OAuth providers, and localhost settings.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth/plugins
	GetNeonAuthPluginConfigs(ctx context.Context, params GetNeonAuthPluginConfigsParams) (*NeonAuthPluginConfigs, error)
	// GetNeonAuthWebhookConfig implements getNeonAuthWebhookConfig operation.
	//
	// Returns the webhook configuration for the specified branch's Neon Auth integration,
	// including the endpoint URL and the events that trigger it.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth/webhooks
	GetNeonAuthWebhookConfig(ctx context.Context, params GetNeonAuthWebhookConfigParams) (*NeonAuthWebhookConfig, error)
	// GetOrganization implements getOrganization operation.
	//
	// Retrieves details for the specified organization, including its name, plan, and configuration.
	//
	// GET /organizations/{org_id}
	GetOrganization(ctx context.Context, params GetOrganizationParams) (*Organization, error)
	// GetOrganizationInvitations implements getOrganizationInvitations operation.
	//
	// Retrieves pending and accepted invitations for the specified organization.
	//
	// GET /organizations/{org_id}/invitations
	GetOrganizationInvitations(ctx context.Context, params GetOrganizationInvitationsParams) (*OrganizationInvitationsResponse, error)
	// GetOrganizationMember implements getOrganizationMember operation.
	//
	// Retrieves information about the specified organization member.
	//
	// GET /organizations/{org_id}/members/{member_id}
	GetOrganizationMember(ctx context.Context, params GetOrganizationMemberParams) (*Member, error)
	// GetOrganizationMembers implements getOrganizationMembers operation.
	//
	// Retrieves a paginated list of members for the specified organization.
	//
	// GET /organizations/{org_id}/members
	GetOrganizationMembers(ctx context.Context, params GetOrganizationMembersParams) (*GetOrganizationMembersOK, error)
	// GetOrganizationSpendingLimit implements getOrganizationSpendingLimit operation.
	//
	// Returns the configured monthly spending limit for the specified organization.
	// `spending_limit_cents: null` indicates that no limit is currently set.
	// Available to organization members with read access on Launch and Scale plans only.
	//
	// GET /organizations/{org_id}/billing/spending_limit
	GetOrganizationSpendingLimit(ctx context.Context, params GetOrganizationSpendingLimitParams) (*SpendingLimitResponse, error)
	// GetOrganizationVPCEndpointDetails implements getOrganizationVPCEndpointDetails operation.
	//
	// Retrieves the current state and configuration details of a specified VPC endpoint.
	//
	// GET /organizations/{org_id}/vpc/region/{region_id}/vpc_endpoints/{vpc_endpoint_id}
	GetOrganizationVPCEndpointDetails(ctx context.Context, params GetOrganizationVPCEndpointDetailsParams) (*VPCEndpointDetails, error)
	// GetProject implements getProject operation.
	//
	// Retrieves information about the specified project.
	// Returned details include the project settings, compute configuration, history retention, owner
	// information, and current usage metrics.
	//
	// GET /projects/{project_id}
	GetProject(ctx context.Context, params GetProjectParams) (*ProjectResponse, error)
	// GetProjectAdvisorSecurityIssues implements getProjectAdvisorSecurityIssues operation.
	//
	// Analyzes the database for security and performance issues.
	// Returns a list of issues categorized by severity (ERROR, WARN, INFO).
	// Requires read access to the project and Data API enabled.
	//
	// GET /projects/{project_id}/advisors
	GetProjectAdvisorSecurityIssues(ctx context.Context, params GetProjectAdvisorSecurityIssuesParams) (*GetProjectAdvisorSecurityIssuesOK, error)
	// GetProjectBranch implements getProjectBranch operation.
	//
	// Retrieves information about the specified branch.
	// A `branch_id` value has a `br-` prefix.
	// Each Neon project is initially created with a root and default branch named `main`.
	// A project can contain one or more branches.
	// A parent branch is identified by a `parent_id` value, which is the `id` of the parent branch.
	// For related information, see [Manage branches](https://neon.com/docs/manage/branches/).
	//
	// GET /projects/{project_id}/branches/{branch_id}
	GetProjectBranch(ctx context.Context, params GetProjectBranchParams) (*GetProjectBranchOK, error)
	// GetProjectBranchAiGateway implements getProjectBranchAiGateway operation.
	//
	// Returns the AI Gateway endpoint host for the specified branch, used to
	// render code-snippet base URLs. A 200 response means the branch is
	// registered and this region serves the AI gateway. A 404 response
	// includes a `reason` field indicating why the gateway is unavailable.
	// **Note**: This endpoint is currently in Private Beta.
	//
	// GET /projects/{project_id}/branches/{branch_id}/ai_gateway
	GetProjectBranchAiGateway(ctx context.Context, params GetProjectBranchAiGatewayParams) (GetProjectBranchAiGatewayRes, error)
	// GetProjectBranchBucketObject implements getProjectBranchBucketObject operation.
	//
	// Streams the raw bytes of the named object from the bucket on the
	// specified branch, including objects inherited from ancestor branches.
	// Served by the user's session (no customer S3 credentials required).
	// The body is returned as `application/octet-stream` so a browser treats
	// it as a download; the `Content-Length` and `ETag` response headers echo
	// the stored object metadata.
	// BINARY-STREAM EXCEPTION TO THE BUILD-GENERATED-TYPES RULE (#7029): the
	// successful 200 body is the raw object stream, proxied verbatim from the
	// platform storage admin endpoint. It is modeled as an
	// `application/octet-stream` binary body (not a JSON response schema) and
	// is streamed without buffering the whole object in memory. Error
	// responses still use the generated `GeneralError` shape.
	// **Note**: This endpoint is currently in Private Beta.
	//
	// GET /projects/{project_id}/branches/{branch_id}/buckets/{bucket_name}/objects/{object_key}/download
	GetProjectBranchBucketObject(ctx context.Context, params GetProjectBranchBucketObjectParams) (GetProjectBranchBucketObjectRes, error)
	// GetProjectBranchDataAPI implements getProjectBranchDataAPI operation.
	//
	// Retrieves the Neon Data API configuration for the specified branch,
	// including endpoint URL, enabled state, and database settings.
	//
	// GET /projects/{project_id}/branches/{branch_id}/data-api/{database_name}
	GetProjectBranchDataAPI(ctx context.Context, params GetProjectBranchDataAPIParams) (*DataAPIReponse, error)
	// GetProjectBranchDatabase implements getProjectBranchDatabase operation.
	//
	// Retrieves information about the specified database.
	// For related information, see [Manage databases](https://neon.com/docs/manage/databases/).
	//
	// GET /projects/{project_id}/branches/{branch_id}/databases/{database_name}
	GetProjectBranchDatabase(ctx context.Context, params GetProjectBranchDatabaseParams) (*DatabaseResponse, error)
	// GetProjectBranchFunction implements getProjectBranchFunction operation.
	//
	// Returns the function identified by its slug.
	// **Note**: This endpoint is currently in Private Beta.
	//
	// GET /projects/{project_id}/branches/{branch_id}/functions/{slug}
	GetProjectBranchFunction(ctx context.Context, params GetProjectBranchFunctionParams) (*NeonFunctionResponse, error)
	// GetProjectBranchRole implements getProjectBranchRole operation.
	//
	// Retrieves details about the specified role.
	// In Neon, the terms "role" and "user" are synonymous.
	// For related information, see [Manage roles](https://neon.com/docs/manage/roles/).
	//
	// GET /projects/{project_id}/branches/{branch_id}/roles/{role_name}
	GetProjectBranchRole(ctx context.Context, params GetProjectBranchRoleParams) (*RoleResponse, error)
	// GetProjectBranchRolePassword implements getProjectBranchRolePassword operation.
	//
	// Retrieves the password for the specified Postgres role, if possible.
	// For related information, see [Manage roles](https://neon.com/docs/manage/roles/).
	//
	// GET /projects/{project_id}/branches/{branch_id}/roles/{role_name}/reveal_password
	GetProjectBranchRolePassword(ctx context.Context, params GetProjectBranchRolePasswordParams) (GetProjectBranchRolePasswordRes, error)
	// GetProjectBranchSchema implements getProjectBranchSchema operation.
	//
	// Retrieves the schema from the specified database. The `lsn` and `timestamp` values cannot be
	// specified at the same time. If both are omitted, the database schema is retrieved from database's
	// head.
	//
	// GET /projects/{project_id}/branches/{branch_id}/schema
	GetProjectBranchSchema(ctx context.Context, params GetProjectBranchSchemaParams) (*BranchSchemaResponse, error)
	// GetProjectBranchSchemaComparison implements getProjectBranchSchemaComparison operation.
	//
	// Compares the schema from the specified database with another branch's schema.
	//
	// GET /projects/{project_id}/branches/{branch_id}/compare_schema
	GetProjectBranchSchemaComparison(ctx context.Context, params GetProjectBranchSchemaComparisonParams) (*BranchSchemaCompareResponse, error)
	// GetProjectBranchStorage implements getProjectBranchStorage operation.
	//
	// Returns whether branchable object-storage is usable for the specified
	// branch. A 200 response means the branch is registered in the storage
	// service and the S3 data plane will accept requests for it. A 404
	// response includes a `reason` field indicating why storage is unavailable.
	// **Note**: This endpoint is currently in Private Beta.
	//
	// GET /projects/{project_id}/branches/{branch_id}/storage
	GetProjectBranchStorage(ctx context.Context, params GetProjectBranchStorageParams) (GetProjectBranchStorageRes, error)
	// GetProjectEndpoint implements getProjectEndpoint operation.
	//
	// Retrieves information about the specified compute endpoint.
	// A compute endpoint is a Neon compute instance.
	// An `endpoint_id` has an `ep-` prefix.
	// For information about compute endpoints, see [Manage computes](https://neon.
	// com/docs/manage/endpoints/).
	//
	// GET /projects/{project_id}/endpoints/{endpoint_id}
	GetProjectEndpoint(ctx context.Context, params GetProjectEndpointParams) (*EndpointResponse, error)
	// GetProjectJWKS implements getProjectJWKS operation.
	//
	// Returns the JWKS URLs available for verifying JWTs used as the authentication mechanism for the
	// specified project.
	//
	// GET /projects/{project_id}/jwks
	GetProjectJWKS(ctx context.Context, params GetProjectJWKSParams) (*ProjectJWKSResponse, error)
	// GetProjectOperation implements getProjectOperation operation.
	//
	// Retrieves details for the specified operation.
	// An operation is an action performed on a Neon project resource.
	//
	// GET /projects/{project_id}/operations/{operation_id}
	GetProjectOperation(ctx context.Context, params GetProjectOperationParams) (*OperationResponse, error)
	// GetSnapshotSchedule implements getSnapshotSchedule operation.
	//
	// Returns the backup schedule for the specified branch, including the configured snapshot
	// frequencies.
	// **Note**: This endpoint is currently in Beta.
	//
	// GET /projects/{project_id}/branches/{branch_id}/backup_schedule
	GetSnapshotSchedule(ctx context.Context, params GetSnapshotScheduleParams) (*BackupSchedule, error)
	// GrantPermissionToProject implements grantPermissionToProject operation.
	//
	// Grants project access to the account associated with the specified email address.
	//
	// POST /projects/{project_id}/permissions
	GrantPermissionToProject(ctx context.Context, req *GrantPermissionToProjectRequest, params GrantPermissionToProjectParams) (*ProjectPermission, error)
	// ListApiKeys implements listApiKeys operation.
	//
	// Retrieves the API keys for your Neon account.
	// The response does not include API key tokens. A token is only provided when creating an API key.
	// API keys can also be managed in the Neon Console.
	// For more information, see [Manage API keys](https://neon.com/docs/manage/api-keys/).
	//
	// GET /api_keys
	ListApiKeys(ctx context.Context) ([]ApiKeysListResponseItem, error)
	// ListBranchNeonAuthOauthProviders implements listBranchNeonAuthOauthProviders operation.
	//
	// Lists the OAuth providers configured for the specified branch's Neon Auth integration.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth/oauth_providers
	ListBranchNeonAuthOauthProviders(ctx context.Context, params ListBranchNeonAuthOauthProvidersParams) (*ListNeonAuthOauthProvidersResponse, error)
	// ListBranchNeonAuthTrustedDomains implements listBranchNeonAuthTrustedDomains operation.
	//
	// Lists the trusted domains in the redirect URI whitelist for the specified branch.
	// Only domains in this list are permitted as redirect targets after authentication.
	//
	// GET /projects/{project_id}/branches/{branch_id}/auth/domains
	ListBranchNeonAuthTrustedDomains(ctx context.Context, params ListBranchNeonAuthTrustedDomainsParams) (*NeonAuthRedirectURIWhitelistResponse, error)
	// ListCredentials implements listCredentials operation.
	//
	// Returns metadata for customer-issued credentials on the branch.
	// Secrets are never included.
	// **Note**: This endpoint is currently in Private Beta.
	//
	// GET /projects/{project_id}/branches/{branch_id}/credentials
	ListCredentials(ctx context.Context, params ListCredentialsParams) (*ListCredentialsResponse, error)
	// ListNeonAuthIntegrations implements listNeonAuthIntegrations operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth` instead.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /projects/{project_id}/auth/integrations
	ListNeonAuthIntegrations(ctx context.Context, params ListNeonAuthIntegrationsParams) (*ListNeonAuthIntegrationsResponse, error)
	// ListNeonAuthOauthProviders implements listNeonAuthOauthProviders operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/oauth_providers` instead. Lists
	// the OAuth providers for the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /projects/{project_id}/auth/oauth_providers
	ListNeonAuthOauthProviders(ctx context.Context, params ListNeonAuthOauthProvidersParams) (*ListNeonAuthOauthProvidersResponse, error)
	// ListNeonAuthRedirectURIWhitelistDomains implements listNeonAuthRedirectURIWhitelistDomains operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/domains` instead. Lists the
	// domains in the redirect_uri whitelist for the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /projects/{project_id}/auth/domains
	ListNeonAuthRedirectURIWhitelistDomains(ctx context.Context, params ListNeonAuthRedirectURIWhitelistDomainsParams) (*NeonAuthRedirectURIWhitelistResponse, error)
	// ListOrgApiKeys implements listOrgApiKeys operation.
	//
	// Retrieves the API keys for the specified organization.
	// The response does not include API key tokens. A token is only provided when creating an API key.
	// API keys can also be managed in the Neon Console.
	// For more information, see [Manage API keys](https://neon.com/docs/manage/api-keys/).
	//
	// GET /organizations/{org_id}/api_keys
	ListOrgApiKeys(ctx context.Context, params ListOrgApiKeysParams) ([]OrgApiKeysListResponseItem, error)
	// ListOrganizationVPCEndpoints implements listOrganizationVPCEndpoints operation.
	//
	// Retrieves the list of VPC endpoints for the specified Neon organization.
	//
	// GET /organizations/{org_id}/vpc/region/{region_id}/vpc_endpoints
	ListOrganizationVPCEndpoints(ctx context.Context, params ListOrganizationVPCEndpointsParams) (*VPCEndpointsResponse, error)
	// ListOrganizationVPCEndpointsAllRegions implements listOrganizationVPCEndpointsAllRegions operation.
	//
	// Retrieves the list of VPC endpoints for the specified Neon organization across all regions.
	//
	// GET /organizations/{org_id}/vpc/vpc_endpoints
	ListOrganizationVPCEndpointsAllRegions(ctx context.Context, params ListOrganizationVPCEndpointsAllRegionsParams) (*VPCEndpointsWithRegionResponse, error)
	// ListProjectBranchBucketObjects implements listProjectBranchBucketObjects operation.
	//
	// Lists objects visible in the named bucket on the specified branch,
	// including those inherited from ancestor branches. Listing is served by
	// the user's session (no customer S3 credentials required).
	// When `delimiter` is supplied (typically `/`), keys are collapsed into
	// common prefixes (`folders`) so callers can render a folder-style
	// browser; keys that do not contain the delimiter after `prefix` are
	// returned as `objects`.
	// **Note**: This endpoint is currently in Private Beta.
	//
	// GET /projects/{project_id}/branches/{branch_id}/buckets/{bucket_name}/objects
	ListProjectBranchBucketObjects(ctx context.Context, params ListProjectBranchBucketObjectsParams) (*BucketObjectsListResponse, error)
	// ListProjectBranchBuckets implements listProjectBranchBuckets operation.
	//
	// Lists branchable object-storage buckets visible on the specified branch,
	// including those inherited from ancestor branches.
	// **Note**: This endpoint is currently in Private Beta.
	//
	// GET /projects/{project_id}/branches/{branch_id}/buckets
	ListProjectBranchBuckets(ctx context.Context, params ListProjectBranchBucketsParams) (*BucketsListResponse, error)
	// ListProjectBranchDatabases implements listProjectBranchDatabases operation.
	//
	// Retrieves a list of databases for the specified branch.
	// A branch can have multiple databases.
	// For related information, see [Manage databases](https://neon.com/docs/manage/databases/).
	//
	// GET /projects/{project_id}/branches/{branch_id}/databases
	ListProjectBranchDatabases(ctx context.Context, params ListProjectBranchDatabasesParams) (*DatabasesResponse, error)
	// ListProjectBranchEndpoints implements listProjectBranchEndpoints operation.
	//
	// Retrieves a list of compute endpoints for the specified branch.
	// Neon permits only one read-write compute endpoint per branch.
	// A branch can have multiple read-only compute endpoints.
	//
	// GET /projects/{project_id}/branches/{branch_id}/endpoints
	ListProjectBranchEndpoints(ctx context.Context, params ListProjectBranchEndpointsParams) (*EndpointsResponse, error)
	// ListProjectBranchFunctions implements listProjectBranchFunctions operation.
	//
	// Lists functions on the specified branch.
	// **Note**: This endpoint is currently in Private Beta.
	//
	// GET /projects/{project_id}/branches/{branch_id}/functions
	ListProjectBranchFunctions(ctx context.Context, params ListProjectBranchFunctionsParams) (*ListProjectBranchFunctionsOK, error)
	// ListProjectBranchRoles implements listProjectBranchRoles operation.
	//
	// Retrieves a list of Postgres roles from the specified branch.
	// For related information, see [Manage roles](https://neon.com/docs/manage/roles/).
	//
	// GET /projects/{project_id}/branches/{branch_id}/roles
	ListProjectBranchRoles(ctx context.Context, params ListProjectBranchRolesParams) (*RolesResponse, error)
	// ListProjectBranches implements listProjectBranches operation.
	//
	// Retrieves a list of branches for the specified project.
	// Each Neon project has a root branch named `main`.
	// A `branch_id` value has a `br-` prefix.
	// A project may contain child branches that were branched from `main` or from another branch.
	// A parent branch is identified by the `parent_id` value, which is the `id` of the parent branch.
	// For related information, see [Manage branches](https://neon.com/docs/manage/branches/).
	//
	// GET /projects/{project_id}/branches
	ListProjectBranches(ctx context.Context, params ListProjectBranchesParams) (*ListProjectBranchesOK, error)
	// ListProjectEndpoints implements listProjectEndpoints operation.
	//
	// Retrieves a list of compute endpoints for the specified project.
	// A compute endpoint is a Neon compute instance.
	// For information about compute endpoints, see [Manage computes](https://neon.
	// com/docs/manage/endpoints/).
	//
	// GET /projects/{project_id}/endpoints
	ListProjectEndpoints(ctx context.Context, params ListProjectEndpointsParams) (*EndpointsResponse, error)
	// ListProjectOperations implements listProjectOperations operation.
	//
	// Retrieves a list of operations for the specified Neon project.
	// The number of operations returned can be large.
	// To paginate the response, issue an initial request with a `limit` value.
	// Then, add the `cursor` value that was returned in the response to the next request.
	// Operations older than 6 months may be deleted from our systems.
	// If you need more history than that, you should store your own history.
	//
	// GET /projects/{project_id}/operations
	ListProjectOperations(ctx context.Context, params ListProjectOperationsParams) (*ListOperations, error)
	// ListProjectPermissions implements listProjectPermissions operation.
	//
	// Retrieves details about users who have access to the project, including the permission `id`, the
	// granted-to email address, and the date project access was granted.
	//
	// GET /projects/{project_id}/permissions
	ListProjectPermissions(ctx context.Context, params ListProjectPermissionsParams) (*ProjectPermissions, error)
	// ListProjectVPCEndpoints implements listProjectVPCEndpoints operation.
	//
	// Lists VPC endpoint restrictions for the specified Neon project.
	//
	// GET /projects/{project_id}/vpc_endpoints
	ListProjectVPCEndpoints(ctx context.Context, params ListProjectVPCEndpointsParams) (*VPCEndpointsResponse, error)
	// ListProjects implements listProjects operation.
	//
	// Retrieves a list of projects for the specified organization.
	// If using a personal API key, include the `org_id` parameter to specify which organization to work
	// with.
	// If using an org API key, `org_id` is automatically inferred from the key.
	// For more information, see [Manage organizations using the Neon API](https://neon.
	// com/docs/manage/orgs-api)
	// and [Manage projects](https://neon.com/docs/manage/projects/).
	//
	// GET /projects
	ListProjects(ctx context.Context, params ListProjectsParams) (*ListProjectsOK, error)
	// ListSharedProjects implements listSharedProjects operation.
	//
	// Retrieves a list of projects shared with your Neon account.
	// For more information, see [Manage projects](https://neon.com/docs/manage/projects/).
	//
	// GET /projects/shared
	ListSharedProjects(ctx context.Context, params ListSharedProjectsParams) (*ListSharedProjectsOK, error)
	// ListSnapshots implements listSnapshots operation.
	//
	// Lists the snapshots for the specified project.
	// Each snapshot represents a point-in-time backup of the project data.
	// **Note**: This endpoint is currently in Beta.
	//
	// GET /projects/{project_id}/snapshots
	ListSnapshots(ctx context.Context, params ListSnapshotsParams) (*ListSnapshotsOK, error)
	// PresignProjectBranchBucketObject implements presignProjectBranchBucketObject operation.
	//
	// Returns a presigned URL that transfers bytes directly to or from the
	// object's bucket on the specified branch, without the caller ever
	// handling S3 credentials. The `operation` field selects the direction:
	// - `upload` returns a presigned `PUT` URL (the caller `PUT`s the file
	// bytes straight to `url` with the returned `headers`). Authorized with
	// project write access.
	// - `download` returns a presigned `GET` URL (the caller `GET`s the
	// bytes straight from `url`). Authorized with project read access.
	// The platform mints a short-lived credential and builds the SigV4-signed
	// URL against the branch's S3 data-plane host, returning it together with
	// the HTTP method, any headers the caller must echo, and the URL's expiry.
	// Served by the user's session (no customer S3 credentials required).
	// **Note**: This endpoint is currently in Private Beta.
	//
	// POST /projects/{project_id}/branches/{branch_id}/buckets/{bucket_name}/objects/{object_key}/presign
	PresignProjectBranchBucketObject(ctx context.Context, req *PresignRequest, params PresignProjectBranchBucketObjectParams) (PresignProjectBranchBucketObjectRes, error)
	// RecoverProject implements recoverProject operation.
	//
	// Recovers a deleted project within the 7-day deletion recovery period.
	// Restores branches, endpoints, settings, and connection strings.
	// Some integrations require manual reconfiguration after recovery.
	// To list recoverable projects, use `GET /projects?recoverable=true`.
	//
	// POST /projects/{project_id}/recover
	RecoverProject(ctx context.Context, params RecoverProjectParams) (*ProjectRecoverResponse, error)
	// RecoverProjectBranch implements recoverProjectBranch operation.
	//
	// Recovers a deleted branch within the 7-day deletion recovery period.
	// The branch must have been soft deleted and not yet permanently deleted.
	// Recovery restores the branch and its endpoints to an idle state.
	// Connection strings remain valid after recovery.
	// TTL branches become non-TTL branches after recovery.
	// To list deleted branches available for recovery, use `GET
	// /projects/{project_id}/branches?include_deleted=true`.
	//
	// POST /projects/{project_id}/branches/{branch_id}/recover
	RecoverProjectBranch(ctx context.Context, params RecoverProjectBranchParams) (*BranchRecoverResponse, error)
	// RemoveOrganizationMember implements removeOrganizationMember operation.
	//
	// Removes the specified member from the organization.
	// Only organization admins can perform this action.
	// The last admin in an organization cannot be removed.
	//
	// DELETE /organizations/{org_id}/members/{member_id}
	RemoveOrganizationMember(ctx context.Context, params RemoveOrganizationMemberParams) error
	// ResetProjectBranchRolePassword implements resetProjectBranchRolePassword operation.
	//
	// Resets the password for the specified Postgres role.
	// Returns a new password and operations. The new password is ready to use when the last operation
	// finishes.
	// The old password remains valid until last operation finishes.
	// Connections to the compute endpoint are dropped. If idle,
	// the compute endpoint becomes active for a short period of time.
	// For related information, see [Manage roles](https://neon.com/docs/manage/roles/).
	//
	// POST /projects/{project_id}/branches/{branch_id}/roles/{role_name}/reset_password
	ResetProjectBranchRolePassword(ctx context.Context, params ResetProjectBranchRolePasswordParams) (*RoleOperations, error)
	// RestartProjectEndpoint implements restartProjectEndpoint operation.
	//
	// Restarts the specified compute endpoint by immediately suspending it and then starting it again.
	// An `endpoint_id` has an `ep-` prefix.
	// For information about compute endpoints, see [Manage computes](https://neon.
	// com/docs/manage/endpoints/).
	//
	// POST /projects/{project_id}/endpoints/{endpoint_id}/restart
	RestartProjectEndpoint(ctx context.Context, params RestartProjectEndpointParams) (*EndpointOperations, error)
	// RestoreProjectBranch implements restoreProjectBranch operation.
	//
	// Restores a branch to an earlier state in its own or another branch's history
	// by specifying an LSN or timestamp.
	// Creates a new branch from the historical state.
	//
	// POST /projects/{project_id}/branches/{branch_id}/restore
	RestoreProjectBranch(ctx context.Context, req *BranchRestoreRequest, params RestoreProjectBranchParams) (*BranchOperations, error)
	// RestoreSnapshot implements restoreSnapshot operation.
	//
	// Restores the specified snapshot to a new branch,
	// and optionally finalizes the restore operation to replace the original branch.
	// **Note**: This endpoint is currently in Beta.
	//
	// POST /projects/{project_id}/snapshots/{snapshot_id}/restore
	RestoreSnapshot(ctx context.Context, req OptRestoreSnapshotReq, params RestoreSnapshotParams) (*RestoredSnapshot, error)
	// RevokeApiKey implements revokeApiKey operation.
	//
	// Revokes the specified API key.
	// An API key that is no longer needed can be revoked.
	// This action cannot be reversed.
	// API keys can also be managed in the Neon Console.
	// See [Manage API keys](https://neon.com/docs/manage/api-keys/).
	//
	// DELETE /api_keys/{key_id}
	RevokeApiKey(ctx context.Context, params RevokeApiKeyParams) (*ApiKeyRevokeResponse, error)
	// RevokeCredential implements revokeCredential operation.
	//
	// Soft-deletes the credential.  Idempotent.
	// **Note**: This endpoint is currently in Private Beta.
	//
	// DELETE /projects/{project_id}/branches/{branch_id}/credentials/{token_id}
	RevokeCredential(ctx context.Context, params RevokeCredentialParams) (RevokeCredentialRes, error)
	// RevokeOrgApiKey implements revokeOrgApiKey operation.
	//
	// Revokes the specified organization API key.
	// An API key that is no longer needed can be revoked.
	// This action cannot be reversed.
	// API keys can also be managed in the Neon Console.
	// See [Manage API keys](https://neon.com/docs/manage/api-keys/).
	//
	// DELETE /organizations/{org_id}/api_keys/{key_id}
	RevokeOrgApiKey(ctx context.Context, params RevokeOrgApiKeyParams) (*OrgApiKeyRevokeResponse, error)
	// RevokePermissionFromProject implements revokePermissionFromProject operation.
	//
	// Revokes project access from the user associated with the specified permission `id`. You can
	// retrieve a user's permission `id` by listing project access.
	//
	// DELETE /projects/{project_id}/permissions/{permission_id}
	RevokePermissionFromProject(ctx context.Context, params RevokePermissionFromProjectParams) (*ProjectPermission, error)
	// SendNeonAuthTestEmail implements sendNeonAuthTestEmail operation.
	//
	// Sends a test email using the configured email server settings to verify SMTP connectivity and
	// credentials.
	// The request body must include the SMTP server settings
	// (`host`, `port`, `username`, `password`, `sender_email`, `sender_name`) and the `recipient_email`
	// address.
	//
	// POST /projects/{project_id}/branches/{branch_id}/auth/send_test_email
	SendNeonAuthTestEmail(ctx context.Context, req *SendNeonAuthTestEmailRequest, params SendNeonAuthTestEmailParams) (*SendNeonAuthTestEmailResponse, error)
	// SetDefaultProjectBranch implements setDefaultProjectBranch operation.
	//
	// Sets the specified branch as the project's default branch.
	// The default designation is automatically removed from the previous default branch.
	// For more information, see [Manage branches](https://neon.com/docs/manage/branches/).
	//
	// POST /projects/{project_id}/branches/{branch_id}/set_as_default
	SetDefaultProjectBranch(ctx context.Context, params SetDefaultProjectBranchParams) (*BranchOperations, error)
	// SetOrganizationSpendingLimit implements setOrganizationSpendingLimit operation.
	//
	// Sets the monthly spending limit for the specified organization.
	// To remove a previously configured limit, send a DELETE request to this endpoint.
	// When a limit is configured, email notifications are sent at 80% and 100% of the limit.
	// Computes are not suspended when the limit is reached.
	// Available to organization admins on Launch and Scale plans only.
	//
	// PUT /organizations/{org_id}/billing/spending_limit
	SetOrganizationSpendingLimit(ctx context.Context, req *SpendingLimitUpdateRequest, params SetOrganizationSpendingLimitParams) (*SpendingLimitResponse, error)
	// SetSnapshotSchedule implements setSnapshotSchedule operation.
	//
	// Updates the backup schedule for the specified branch.
	// The schedule defines how often automatic snapshots are created (e.g., `hourly`, `daily`).
	// **Note**: This endpoint is currently in Beta.
	//
	// PUT /projects/{project_id}/branches/{branch_id}/backup_schedule
	SetSnapshotSchedule(ctx context.Context, req *BackupSchedule, params SetSnapshotScheduleParams) error
	// StartAnonymization implements startAnonymization operation.
	//
	// Starts the anonymization process for an anonymized branch that is in the initialized, error, or
	// anonymized state.
	// This will apply all defined masking rules to anonymize sensitive data in the branch databases.
	// The branch must be an anonymized branch to start anonymization.
	// **Note**: This endpoint is currently in Beta.
	//
	// POST /projects/{project_id}/branches/{branch_id}/anonymize
	StartAnonymization(ctx context.Context, params StartAnonymizationParams) (*AnonymizedBranchStatusResponse, error)
	// StartProjectEndpoint implements startProjectEndpoint operation.
	//
	// Starts a compute endpoint.
	// The compute endpoint is ready to use after the last operation in the chain finishes successfully.
	// An `endpoint_id` has an `ep-` prefix.
	// For information about compute endpoints, see [Manage computes](https://neon.
	// com/docs/manage/endpoints/).
	//
	// POST /projects/{project_id}/endpoints/{endpoint_id}/start
	StartProjectEndpoint(ctx context.Context, params StartProjectEndpointParams) (*EndpointOperations, error)
	// SuspendProjectEndpoint implements suspendProjectEndpoint operation.
	//
	// Suspends the specified compute endpoint.
	// An `endpoint_id` has an `ep-` prefix.
	// For information about compute endpoints, see [Manage computes](https://neon.
	// com/docs/manage/endpoints/).
	//
	// POST /projects/{project_id}/endpoints/{endpoint_id}/suspend
	SuspendProjectEndpoint(ctx context.Context, params SuspendProjectEndpointParams) (*EndpointOperations, error)
	// TransferNeonAuthProviderProject implements transferNeonAuthProviderProject operation.
	//
	// Transfers ownership of your Neon-managed auth project to your own auth provider account.
	//
	// POST /projects/auth/transfer_ownership
	TransferNeonAuthProviderProject(ctx context.Context, req *NeonAuthTransferAuthProviderProjectRequest) (*NeonAuthTransferAuthProviderProjectResponse, error)
	// TransferProjectsFromOrgToOrg implements transferProjectsFromOrgToOrg operation.
	//
	// Transfers selected projects, identified by their IDs, from your organization to another specified
	// organization.
	//
	// POST /organizations/{source_org_id}/projects/transfer
	TransferProjectsFromOrgToOrg(ctx context.Context, req *TransferProjectsToOrganizationRequest, params TransferProjectsFromOrgToOrgParams) (TransferProjectsFromOrgToOrgRes, error)
	// TransferProjectsFromUserToOrg implements transferProjectsFromUserToOrg operation.
	//
	// DEPRECATED. Personal accounts have been migrated to organizations, making this operation no longer
	// applicable.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /users/me/projects/transfer
	TransferProjectsFromUserToOrg(ctx context.Context, req *TransferProjectsToOrganizationRequest) (TransferProjectsFromUserToOrgRes, error)
	// UpdateBranchNeonAuthOauthProvider implements updateBranchNeonAuthOauthProvider operation.
	//
	// Updates a OAuth provider for the specified project.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/auth/oauth_providers/{oauth_provider_id}
	UpdateBranchNeonAuthOauthProvider(ctx context.Context, req *NeonAuthUpdateOAuthProviderRequest, params UpdateBranchNeonAuthOauthProviderParams) (*NeonAuthOauthProvider, error)
	// UpdateMaskingRules implements updateMaskingRules operation.
	//
	// Updates the masking rules for the specified anonymized branch.
	// Masking rules define how sensitive data should be anonymized using PostgreSQL Anonymizer.
	// **Note**: This endpoint is currently in Beta.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/masking_rules
	UpdateMaskingRules(ctx context.Context, req *MaskingRulesUpdateRequest, params UpdateMaskingRulesParams) (*MaskingRulesResponse, error)
	// UpdateNeonAuthAllowLocalhost implements updateNeonAuthAllowLocalhost operation.
	//
	// Updates the localhost allow setting for the specified branch's Neon Auth integration.
	// When enabled, authentication flows work from `localhost` without adding it to the redirect URI
	// whitelist.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/auth/allow_localhost
	UpdateNeonAuthAllowLocalhost(ctx context.Context, req *UpdateNeonAuthAllowLocalhostRequest, params UpdateNeonAuthAllowLocalhostParams) (*NeonAuthAllowLocalhostResponse, error)
	// UpdateNeonAuthConfig implements updateNeonAuthConfig operation.
	//
	// Updates the auth configuration for the branch.
	// Currently supports updating the application name used in auth emails.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/auth/config
	UpdateNeonAuthConfig(ctx context.Context, req *NeonAuthConfigUpdate, params UpdateNeonAuthConfigParams) (*NeonAuthConfigResponse, error)
	// UpdateNeonAuthEmailAndPasswordConfig implements updateNeonAuthEmailAndPasswordConfig operation.
	//
	// Updates the email and password authentication configuration for the specified branch's Neon Auth
	// integration.
	// Only the fields provided in the request body are updated.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/auth/email_and_password
	UpdateNeonAuthEmailAndPasswordConfig(ctx context.Context, req *NeonAuthEmailAndPasswordConfigUpdate, params UpdateNeonAuthEmailAndPasswordConfigParams) (*NeonAuthEmailAndPasswordConfig, error)
	// UpdateNeonAuthEmailProvider implements updateNeonAuthEmailProvider operation.
	//
	// Updates the email provider configuration for the specified branch's Neon Auth integration.
	// The email provider handles transactional messages such as verification emails and password reset
	// links.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/auth/email_provider
	UpdateNeonAuthEmailProvider(ctx context.Context, req *NeonAuthEmailServerConfig, params UpdateNeonAuthEmailProviderParams) (*NeonAuthEmailServerConfig, error)
	// UpdateNeonAuthEmailServer implements updateNeonAuthEmailServer operation.
	//
	// DEPRECATED, use `/projects/{project_id}/branches/{branch_id}/auth/email_provider` instead. Updates
	// the email server configuration for the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// PATCH /projects/{project_id}/auth/email_server
	UpdateNeonAuthEmailServer(ctx context.Context, req *NeonAuthEmailServerConfig, params UpdateNeonAuthEmailServerParams) (*NeonAuthEmailServerConfig, error)
	// UpdateNeonAuthMagicLinkPlugin implements updateNeonAuthMagicLinkPlugin operation.
	//
	// Updates the magic link plugin configuration for Neon Auth.
	// The magic link plugin enables passwordless authentication via email magic links.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/auth/plugins/magic-link
	UpdateNeonAuthMagicLinkPlugin(ctx context.Context, req *NeonAuthMagicLinkConfigUpdate, params UpdateNeonAuthMagicLinkPluginParams) (*NeonAuthMagicLinkConfig, error)
	// UpdateNeonAuthOauthProvider implements updateNeonAuthOauthProvider operation.
	//
	// DEPRECATED, use
	// `/projects/{project_id}/branches/{branch_id}/auth/oauth_providers/{oauth_provider_id}` instead.
	// Updates a OAuth provider for the specified project.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// PATCH /projects/{project_id}/auth/oauth_providers/{oauth_provider_id}
	UpdateNeonAuthOauthProvider(ctx context.Context, req *NeonAuthUpdateOAuthProviderRequest, params UpdateNeonAuthOauthProviderParams) (*NeonAuthOauthProvider, error)
	// UpdateNeonAuthOrganizationPlugin implements updateNeonAuthOrganizationPlugin operation.
	//
	// Updates the organization plugin configuration for Neon Auth.
	// The organization plugin enables multi-tenant organization support.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/auth/plugins/organization
	UpdateNeonAuthOrganizationPlugin(ctx context.Context, req *NeonAuthOrganizationConfigUpdate, params UpdateNeonAuthOrganizationPluginParams) (*NeonAuthOrganizationConfig, error)
	// UpdateNeonAuthPhoneNumberPlugin implements updateNeonAuthPhoneNumberPlugin operation.
	//
	// Updates the phone number plugin configuration for Neon Auth.
	// Only the fields provided in the request body are updated; omitted fields retain their current
	// values.
	// The phone number plugin enables phone-based OTP authentication.
	// OTP codes are delivered via the `send.otp` webhook event with `delivery_preference: "sms"`.
	// A webhook must be configured with the `send.otp` event enabled for SMS delivery to work.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/auth/plugins/phone-number
	UpdateNeonAuthPhoneNumberPlugin(ctx context.Context, req *NeonAuthPhoneNumberConfigUpdate, params UpdateNeonAuthPhoneNumberPluginParams) (*NeonAuthPhoneNumberConfig, error)
	// UpdateNeonAuthUserRole implements updateNeonAuthUserRole operation.
	//
	// Updates the role of a user in the Neon Auth user directory for the specified branch.
	// The role controls the user's level of access within the Neon Auth integration.
	//
	// PUT /projects/{project_id}/branches/{branch_id}/auth/users/{auth_user_id}/role
	UpdateNeonAuthUserRole(ctx context.Context, req *UpdateNeonAuthUserRoleRequest, params UpdateNeonAuthUserRoleParams) (*UpdateNeonAuthUserRoleResponse, error)
	// UpdateNeonAuthWebhookConfig implements updateNeonAuthWebhookConfig operation.
	//
	// Updates the webhook configuration for the specified branch's Neon Auth integration.
	// Webhooks notify an external endpoint when auth events occur, such as user creation or sign-in.
	//
	// PUT /projects/{project_id}/branches/{branch_id}/auth/webhooks
	UpdateNeonAuthWebhookConfig(ctx context.Context, req *NeonAuthWebhookConfig, params UpdateNeonAuthWebhookConfigParams) (*NeonAuthWebhookConfig, error)
	// UpdateOrganizationMember implements updateOrganizationMember operation.
	//
	// Updates the role of an existing member in the specified organization.
	// The requested role must be valid for the organization.
	// Only organization admins can call this endpoint.
	//
	// PATCH /organizations/{org_id}/members/{member_id}
	UpdateOrganizationMember(ctx context.Context, req *OrganizationMemberUpdateRequest, params UpdateOrganizationMemberParams) (*Member, error)
	// UpdateProject implements updateProject operation.
	//
	// Updates the specified project.
	// Configurable properties include the project name, default compute settings, history retention
	// period, and IP allowlist.
	//
	// PATCH /projects/{project_id}
	UpdateProject(ctx context.Context, req *ProjectUpdateRequest, params UpdateProjectParams) (*UpdateProjectOK, error)
	// UpdateProjectBranch implements updateProjectBranch operation.
	//
	// Updates the specified branch.
	// For more information, see [Manage branches](https://neon.com/docs/manage/branches/).
	//
	// PATCH /projects/{project_id}/branches/{branch_id}
	UpdateProjectBranch(ctx context.Context, req *BranchUpdateRequest, params UpdateProjectBranchParams) (*BranchOperations, error)
	// UpdateProjectBranchDataAPI implements updateProjectBranchDataAPI operation.
	//
	// Updates the Neon Data API configuration for the specified branch.
	// You can optionally provide settings to update the Data API configuration.
	// The schema cache is always refreshed as part of this operation.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/data-api/{database_name}
	UpdateProjectBranchDataAPI(ctx context.Context, req OptDataAPIUpdateRequest, params UpdateProjectBranchDataAPIParams) error
	// UpdateProjectBranchDatabase implements updateProjectBranchDatabase operation.
	//
	// Updates the specified database in the branch.
	// For related information, see [Manage databases](https://neon.com/docs/manage/databases/).
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/databases/{database_name}
	UpdateProjectBranchDatabase(ctx context.Context, req *DatabaseUpdateRequest, params UpdateProjectBranchDatabaseParams) (*DatabaseOperations, error)
	// UpdateProjectBranchFunction implements updateProjectBranchFunction operation.
	//
	// Updates the function's mutable metadata — currently only the display
	// `name`. A string sets the display name; `null` clears it, after which
	// the function's `name` falls back to its slug. Leading and trailing
	// whitespace is trimmed; a whitespace-only name is rejected. Acts only
	// on a function owned by the branch: a slug that is only inherited from
	// an ancestor branch returns 404 — rename it on the branch that owns
	// it. Like every other change on a branch, a rename is isolated per
	// branch: a branch forked before the rename keeps the name it had at
	// fork time.
	// **Note**: This endpoint is currently in Private Beta.
	//
	// PATCH /projects/{project_id}/branches/{branch_id}/functions/{slug}
	UpdateProjectBranchFunction(ctx context.Context, req *NeonFunctionUpdateRequest, params UpdateProjectBranchFunctionParams) (*NeonFunctionResponse, error)
	// UpdateProjectEndpoint implements updateProjectEndpoint operation.
	//
	// Updates the specified compute endpoint.
	// An `endpoint_id` has an `ep-` prefix. A `branch_id` has a `br-` prefix.
	// For more information about compute endpoints, see [Manage computes](https://neon.
	// com/docs/manage/endpoints/).
	// If the returned list of operations is not empty, the compute endpoint is not ready to use.
	// The client must wait for the last operation to finish before using the compute endpoint.
	// If the compute endpoint was idle before the update, it becomes active for a short period of time,
	// and the control plane suspends it again after the update.
	//
	// PATCH /projects/{project_id}/endpoints/{endpoint_id}
	UpdateProjectEndpoint(ctx context.Context, req *EndpointUpdateRequest, params UpdateProjectEndpointParams) (*EndpointOperations, error)
	// UpdateSnapshot implements updateSnapshot operation.
	//
	// Updates the specified snapshot.
	// **Note**: This endpoint is currently in Beta.
	//
	// PATCH /projects/{project_id}/snapshots/{snapshot_id}
	UpdateSnapshot(ctx context.Context, req *SnapshotUpdateRequest, params UpdateSnapshotParams) (*UpdateSnapshotOK, error)
	// NewError creates *GeneralErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GeneralErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
